// src/lexikon/lexikonIndex.en.ts
// Carlos' Lexicon — English translations of all entries.

import type { LexikonEntry } from './lexikonTypes';

export const LEXIKON_ENTRIES_EN: LexikonEntry[] = [
  {
    id: 'admin',
    title: 'Admin',
    teaser: 'The person who manages a group or chat and sets the rules.',
    body: 'Admin is short for "Administrator" — meaning someone who manages things. In a group chat, the admin is the person who created the group or took control of it. The admin can add or remove people, set rules, and sometimes delete messages. Whoever is admin has more power than the other members.',
    didYouKnow: 'The word "administrator" comes from Latin and means "the one who manages". Online it\'s almost always shortened to "admin".',
    firstAppearance: 's1e02c06',
  },
  {
    id: 'algorithmus',
    title: 'Algorithm',
    teaser: 'A step-by-step set of instructions that tells an app what to do.',
    body: 'An algorithm is a precise sequence of rules that a program uses to make decisions. In social media apps, it decides which videos you see first — based on what you\'ve watched, liked, or spent time on so far. Think of it like a person writing down everything you watch each day — and then showing you more and more of it. That\'s exactly what an algorithm does — automatically and without a break.',
    didYouKnow: 'The word comes from the mathematician al-Khwarizmi from the 9th century. His name was later turned into "algorithm".',
    firstAppearance: 's1e03c03',
  },
  {
    id: 'amic',
    title: 'Amic',
    teaser: 'The new app format — an interactive chat between Amy and you.',
    body: 'The new app format. Amic is a blend of Amy — the owl Amy Surfwing — and Comic. Amics are written like chats and filled with images. They are interactive and guide the reader into Amy\'s world, where she shares tips and tricks about the digital world through a fictional school newspaper, secret diaries, and sticker albums.',
    didYouKnow: '"Amic" is made up of "Amy" and "Comic" — a blend word that describes exactly what it is: Amy\'s world experienced as a chat comic.',
  },
  {
    id: 'avatar',
    title: 'Avatar',
    teaser: 'The image or character that represents you online.',
    body: 'An avatar is the image or character that represents you online. It can look like you — but it doesn\'t have to. The word comes from Sanskrit and originally meant the appearance of a god on earth. On the internet it\'s your digital appearance — you decide what it looks like.',
    didYouKnow: 'The word "avatar" was first used in the digital sense in 1985 in the computer game "Habitat" — long before social media existed.',
  },
  {
    id: 'blog',
    title: 'Blog',
    teaser: 'A website where someone regularly publishes their own texts.',
    body: 'A blog is a website where someone shares their thoughts or information on the internet — for anyone who wants to read along. Usually all the entries are about the same topic, for example travel, sport, or recipes. A blog is not a verified newspaper. Just because something is written there doesn\'t automatically mean it\'s true.',
    didYouKnow: 'The word "blog" comes from "weblog" — an online diary. The first blogs appeared in the 1990s, long before Instagram and TikTok.',
  },
  {
    id: 'challenge',
    title: 'Challenge',
    teaser: 'A voluntary task that you set yourself or take on with others.',
    body: 'A challenge is a voluntary task you take on to push yourself. For example, practising something every day, trying something new, or overcoming a small fear. Often you do it together with others so you can motivate each other. You should always check whether the task is actually worthwhile — and not just risky or dangerous.',
    didYouKnow: 'Not all internet challenges are harmless. Some were specifically designed to get as many people as possible to do something risky. So: always think before you join in.',
  },
  {
    id: 'chat',
    title: 'Chat',
    teaser: 'A digital conversation — fast and direct, but easily misunderstood.',
    body: 'A chat is a digital conversation where messages are exchanged in real time or with a short delay. Usually faster than talking — but also easier to misunderstand. Tone and facial expressions are completely absent, so many misunderstandings arise in chats that would never happen in real life.',
    didYouKnow: 'Up to 93% of communication is missing in a chat — gestures, facial expressions, and voice. What\'s meant as a joke can easily come across the wrong way.',
  },
  {
    id: 'cloud',
    title: 'Cloud',
    teaser: 'Storage space on the internet — not an actual cloud, but rain-proof.',
    body: 'The cloud is storage space on the internet. Not an actual cloud. Rain-proof. Instead of saving files only on your own device, they\'re stored on servers somewhere in the world — and are accessible from anywhere. That\'s handy, but it also means: the data is held by a company, not just by you.',
    didYouKnow: '"The cloud" is really just another name for "someone else\'s computer". The servers are housed in enormous data centres — some as big as several football pitches.',
  },
  {
    id: 'condo-games',
    title: 'Condo Games',
    teaser: 'Online game spaces that are not always safe for children.',
    body: 'Condo games are online games or virtual spaces where players can design their own rooms or apartments and meet others there — like a digital hangout in a self-built world. The problem is that some of these spaces are not well monitored, and content or conversations can appear that aren\'t meant for children.',
    didYouKnow: 'Platforms like Roblox have special systems to detect and block such spaces. Even so, they keep appearing — which is why it\'s important to talk with adults about online experiences.',
  },
  {
    id: 'datenschutz',
    title: 'Data Protection',
    teaser: 'The right that personal data cannot simply be used by anyone.',
    body: 'Data protection means that personal information cannot simply be seen or used by everyone. It ensures that companies and apps must follow rules when they store or pass on data. It matters because information about you could otherwise be used against you — for example through manipulative advertising, fraud, or unwanted surveillance.',
    didYouKnow: 'In the EU, the GDPR (General Data Protection Regulation) protects everyone. Companies that violate it can face fines running into billions.',
  },
  {
    id: 'fake-news',
    title: 'Fake News',
    teaser: 'Deliberately false or misleading information.',
    body: 'Fake news is information that is intentionally spread in a false or heavily distorted way — often to generate clicks, influence opinions, or cause confusion. Not every piece of incorrect information is fake news: mistakes happen. Fake news is deliberate. Warning signs: sensational headlines, missing sources, emotionally charged language, no date. Always check several independent sources.',
    didYouKnow: 'False news spreads on average six times faster than true news — as shown by an MIT study.',
    firstAppearance: 's1e03c03',
  },
  {
    id: 'feed',
    title: 'Feed',
    teaser: 'The endless stream of content that an algorithm selects for you.',
    body: 'The feed is the list of posts, videos, or images shown to you in an app when you scroll. On Instagram, TikTok, or YouTube: one video, then the next, then another. The feed is like an endless stream of content. What appears in it is often decided by an algorithm — and it doesn\'t show things randomly, but mostly what keeps you watching as long as possible.',
    didYouKnow: 'The term "feed" comes from "to feed" — the app feeds you content. That\'s no accident: the word was chosen deliberately because it describes exactly what happens.',
  },
  {
    id: 'filter',
    title: 'Filter',
    teaser: 'A function that changes images — and rarely makes them more realistic.',
    body: 'A filter is a function that alters images. It rarely makes things more realistic. Filters can change colours, brightness, skin tone, shape, and even facial features — some in seconds, almost beyond recognition. The problem: when many images are filtered, what counts as "normal" shifts.',
    didYouKnow: 'Some studies show that regular filter use changes body image — young people start to see their unfiltered appearance as "wrong".',
  },
  {
    id: 'follower',
    title: 'Follower',
    teaser: 'People who voluntarily follow an account and see its content.',
    body: 'Followers are people who voluntarily follow an account. Not to be confused with actual stalkers. Most of the time they don\'t know you personally. Having many followers means reach — but not necessarily that the content is good or accurate. Follower counts can also be bought.',
    didYouKnow: 'Around 15% of all social media followers on major platforms are said to be "fake accounts" or bots — not real people at all.',
  },
  {
    id: 'fomo',
    title: 'FOMO',
    teaser: 'The fear of missing out while everyone else is having fun.',
    body: 'FOMO stands for "Fear Of Missing Out". It means the fear of missing something while everyone else is apparently having a great time. FOMO doesn\'t arise because everything really is incredibly important. It arises because you can constantly see what others are doing. In the past, you simply missed things. Today, you\'re constantly reminded of them.',
    didYouKnow: 'Studies show that FOMO is especially strong on phones — because notifications constantly remind you of what you might be missing.',
  },
  {
    id: 'gamer',
    title: 'Gamer',
    teaser: 'A person who regularly plays video games.',
    body: 'A gamer is a person who regularly plays video games. Not automatically a career. Gaming is one of the biggest leisure activities in the world — with over 3 billion players. Professional gaming (eSports) is actually a career, but only for a very small number of people.',
    didYouKnow: 'The gaming industry makes more revenue than cinema and music combined. The first video game was invented in 1958 by a physicist — as an experiment, not for entertainment.',
  },
  {
    id: 'geodaten',
    title: 'Location Data',
    teaser: 'Location information that reveals where you have been.',
    body: 'Location data is digital information that describes a place on earth — for example GPS coordinates. Every time your phone uses an app with location access, your whereabouts are stored. Some apps genuinely need this (navigation), others simply collect it because they make money from it. A complete movement history reveals almost everything about a person\'s daily life.',
    didYouKnow: 'With your phone\'s location data, someone can say pretty precisely where you sleep, go to school, and spend your free time every day.',
    firstAppearance: 's1e03c03',
  },
  {
    id: 'google-earth',
    title: 'Google Earth',
    teaser: 'The entire earth on screen — right down to a single house.',
    body: 'Google Earth is a computer program by Google that lets you look at the earth from above. Really the whole earth. You can zoom in to individual houses, "drive" through streets, and see places you\'ve never been to.',
    didYouKnow: 'The satellite images in Google Earth are not always up to date. Some images are several years old. But the resolution is still good enough to recognise individual cars.',
  },
  {
    id: 'grooming',
    title: 'Grooming',
    teaser: 'When an adult tricks a child into trusting them — in order to exploit them.',
    body: 'Grooming means that an adult deliberately builds the trust of a child or young person online. The person first appears friendly, interested, and understanding in order to build a relationship. The aim is usually to get personal information, images, or a meeting in real life. Important: if someone online demands secrets, puts on pressure, or conversations suddenly become uncomfortable, talk to a trusted adult immediately.',
    didYouKnow: 'Grooming often happens over a long time — weeks or months. The person affected often doesn\'t notice for a long time that something is wrong. So remember: uncomfortable feeling = speak up right away, no matter what.',
  },
  {
    id: 'hashtag',
    title: 'Hashtag (#)',
    teaser: 'A word with # in front of it, making content searchable by topic.',
    body: 'A hashtag is a word with a hash symbol in front of it, so content is easier to find. No, it\'s not a waffle grid. Clicking on a hashtag shows all posts with the same tag. That makes it easy to follow topics — but also easy to make content artificially more visible.',
    didYouKnow: 'The first Twitter hashtag was proposed in 2007 by Chris Messina — Twitter initially thought the idea was "too nerdy". Today hashtags are standard on almost every platform.',
  },
  {
    id: 'influencer',
    title: 'Influencer',
    teaser: 'A person on the internet who influences others with their recommendations.',
    body: 'A person on the internet who acts as if they\'re only showing their life, but is actually also advertising things. Sometimes you can\'t immediately tell the difference. Influencers have many followers and use this to spread products or opinions — paid or unpaid. In many countries, paid advertising posts must be labelled as advertising. Not everyone follows this rule.',
    didYouKnow: 'Studies show that advertising by influencers is often perceived by young people as less like advertising than classic TV ads — even though it\'s equally paid.',
  },
  {
    id: 'ki',
    title: 'AI (Artificial Intelligence)',
    teaser: 'Systems that recognise patterns and derive decisions from them.',
    body: 'AI stands for Artificial Intelligence — programmes that "learn" from examples instead of following fixed rules. They recognise patterns in huge amounts of data and can, for example, describe images, translate texts, or predict what you\'ll want to buy or watch next. AI doesn\'t make decisions like a human. It calculates probabilities — what is most likely to fit.',
    didYouKnow: 'AI systems make mistakes — often in predictable ways. If the training data is one-sided, the results will be too.',
    firstAppearance: 's1e03c03',
  },
  {
    id: 'ki-bilder',
    title: 'AI Images',
    teaser: 'Images that no human made — but a computer program.',
    body: 'AI images are images that aren\'t taken by a camera or drawn by a person, but generated by a computer program. They can look very real. That makes it harder to recognise what actually happened and what was invented. Some AI images show people, places, or events that never existed — but look deceptively real.',
    didYouKnow: 'Some AI images are so realistic that even experts can barely tell them apart from real photos. That\'s why reverse image search is so important.',
  },
  {
    id: 'kommentar',
    title: 'Comment',
    teaser: 'A public opinion below a post — visible to everyone.',
    body: 'A comment is a public opinion below a post. Quality varies enormously. Comments are public and often remain visible for a long time. What is written in the heat of the moment cannot be taken back — even if you delete the comment, it may already have been saved or forwarded.',
    didYouKnow: 'Studies show that negative comments have up to five times more emotional impact than positive ones — a mean comment stays in memory longer than ten nice ones.',
  },
  {
    id: 'like',
    title: 'Like',
    teaser: 'A click that shows approval — but doesn\'t always mean real interest.',
    body: 'A like is a click that shows approval. It doesn\'t automatically mean someone has really engaged with the content. Many people like posts after just a few seconds — without having really read or watched them. Yet likes work on many people like a kind of rating: lots of likes = good, few likes = bad. That can be quite a lot of pressure.',
    didYouKnow: 'Facebook originally wanted to introduce a "dislike" button. Instead this became the system of various reactions — because a pure dislike would have created too much negativity.',
  },
  {
    id: 'link',
    title: 'Link',
    teaser: 'A clickable connection to another page on the internet.',
    body: 'A link is a clickable connection to another page or file on the internet. Usually blue or underlined — and leads somewhere else. When you click on it, you jump straight to new information, a video, or a website. Caution: not every link leads where it claims to go. You shouldn\'t just click on unknown links.',
    didYouKnow: 'The World Wide Web was invented in 1989 by Tim Berners-Lee — and the link was his central idea. Without links, the internet would be a pile of disconnected pages.',
  },
  {
    id: 'livestream',
    title: 'Livestream',
    teaser: 'A broadcast in real time — mistakes happen in front of an audience.',
    body: 'A livestream is a broadcast in real time. Mistakes happen in front of an audience. On platforms like Twitch, YouTube, or TikTok, people can broadcast live — and viewers comment at the same time. What was once live may have been recorded — even without you noticing.',
    didYouKnow: 'The first major music livestream was in 1993 — a concert by the band Severe Tire Damage. Back then only a few thousand people could watch. Today millions watch simultaneously.',
  },
  {
    id: 'meme',
    title: 'Meme',
    teaser: 'Images, videos, or texts that are shared as a joke.',
    body: 'A meme (pronounced "meem") is an image, video, or text that is quickly shared and often adapted on the internet. Usually it\'s a joke based on a well-known template. The word originally comes from evolutionary biology — a "meme" is an idea that spreads like a gene. Internet memes work similarly: they mutate, get passed on, and change in the process.',
    didYouKnow: 'The term "meme" was invented in 1976 by biologist Richard Dawkins — long before the internet.',
    firstAppearance: 's1e03c01',
  },
  {
    id: 'metadaten',
    title: 'Metadata',
    teaser: 'Data about data — what was saved when and where.',
    body: 'Metadata is information that describes how, when, and where something was created — not the content itself, but the context around it. A photo on your phone saves — alongside the image — when it was taken, with which device, and often even where. A message saves: who wrote it, when, and to whom. Many apps collect metadata even if they can\'t see the actual content.',
    didYouKnow: 'Former NSA director Keith Alexander once said: "We don\'t collect content — just metadata." But from metadata alone, a great deal can be found out about a person.',
    firstAppearance: 's1e03c03',
  },
  {
    id: 'newsletter',
    title: 'Newsletter',
    teaser: 'A regular email with news on a specific topic.',
    body: 'A newsletter is a regular email with news on a specific topic. For example from a newspaper, a company, or a club. Newsletters only go to people who have signed up for them — unlike spam, which arrives uninvited.',
    didYouKnow: 'Over 300 billion emails are sent worldwide every day — a large proportion of these are newsletters and advertising emails.',
  },
  {
    id: 'offline-zeit',
    title: 'Offline Time',
    teaser: 'Intentional breaks from your phone and the internet — to regain perspective.',
    body: 'Offline time is a voluntary break from your phone, chat, or the internet. Not a punishment or a ban — but a conscious experiment: What does it feel like to be unreachable for an hour, an evening, or a whole day? Many people notice for the first time how automatically they reach for their phone. Offline time helps you understand your own usage habits better and engage with technology more intentionally.',
    didYouKnow: 'Studies show that even short periods of offline time can lower stress levels — because you stop waiting for the next notification.',
    firstAppearance: 's1e03c06',
  },
  {
    id: 'offline-challenge',
    title: 'Offline Challenge',
    teaser: 'Deliberately going without your phone or internet for a while.',
    body: 'An offline challenge is a self-set experiment: put the phone down, switch off the internet — for an hour, a day, or a week. The aim isn\'t to demonise technology, but to find out how dependent you really are, and whether you\'d like to use the time differently. Many people afterwards report better concentration, better sleep, and a feeling of having more time.',
    didYouKnow: 'Some schools in Finland hold regular "Screen-free Fridays" — and students report feeling more rested at the weekend.',
    firstAppearance: 's1e03c01',
  },
  {
    id: 'omg',
    title: 'OMG',
    teaser: 'Abbreviation for "Oh My God" — expressing surprise or shock.',
    body: 'OMG is an abbreviation for "Oh My God". It means something like: "Oh wow!" — an exclamation when you\'re surprised, shocked, or extremely impressed. It\'s used constantly in chats and on social media — usually more as an exclamation than genuine surprise.',
    didYouKnow: 'OMG is older than the internet. The first known use was in 1917 in a letter from a British admiral — long before WhatsApp.',
  },
  {
    id: 'posts',
    title: 'Posts',
    teaser: 'Content that someone publishes publicly on the internet.',
    body: 'Posts are content that someone publishes on the internet. For example a photo, a video, a text, or all of these together. Once something is posted, it can spread quickly — even if you delete it later. On the internet: nothing is really gone as long as someone has seen or saved it.',
    didYouKnow: 'On average, over 500,000 photos are posted on Instagram alone every minute — and yet most people see only a tiny fraction of them.',
  },
  {
    id: 'profil',
    title: 'Profile',
    teaser: 'Your digital self-presentation — often a curated version of you.',
    body: 'A profile is your digital self-presentation. Not always identical to the real version of you. In your profile you decide what others are allowed to see — picture, name, description, posts. That\'s a power, but also a responsibility: what you show influences how others perceive you.',
    didYouKnow: 'Studies show that people present their social media profiles on average more positively than they rate themselves — more smiling, more successes, fewer bad days.',
  },
  {
    id: 'prompt',
    title: 'Prompt',
    teaser: 'The instruction you give an AI so it does something.',
    body: 'A prompt is the instruction or question you enter into an AI so it does something. For example a text, an idea, or a description for an image. The more precise the prompt, the better the AI understands what is meant. A short or unclear prompt often leads to surprising results.',
    didYouKnow: '"Prompt engineering" is now a real job — people are paid to develop especially good instructions for AI systems.',
  },
  {
    id: 'reverse-image-search',
    title: 'Reverse Image Search',
    teaser: 'Use an image as a search term — and find out if it\'s real.',
    body: 'In a reverse image search you don\'t upload a word, but an image. The search engine then searches the entire internet for the same or similar images. This lets you find out: does this photo really come from here? Has it been used before? And: is the context even right? Especially in misinformation, real photos from a completely different context are recycled — for example an old photo of a fight that suddenly circulates as evidence of something current. A reverse image search can often expose this in seconds. Tools: Google Images (images.google.com → camera icon), TinEye, or the Google Lens function on your phone.',
    didYouKnow: 'The method is used daily by journalists and fact-checkers — for example by the well-known fact-checking project "Bellingcat". You can use it too to expose a fake in seconds.',
    firstAppearance: 's1e02c02',
  },
  {
    id: 'rueckwaertssuche',
    title: 'Reverse Image Search',
    teaser: 'Upload an image and find out where else it appears.',
    body: 'In a normal search you enter words. In a reverse image search you enter an image instead — and the search engine finds out where else that image appears on the internet. This is useful for exposing fake images or finding the origin of a photo. But also for everyday things: what\'s that animal called? Which plant is this? Which shop sells this rucksack? Google Images and TinEye offer this.',
    didYouKnow: 'Many false stories online use real photos in the wrong context. A reverse image search can often expose this in seconds.',
    firstAppearance: 's1e03c03',
  },
  {
    id: 'screen-time',
    title: 'Screen Time',
    teaser: 'The time you spend in front of screens every day.',
    body: 'Screen time refers to the total time someone looks at screens each day — phone, tablet, computer, TV. On smartphones, usage can usually be checked in the settings, broken down by app. Many apps are designed to increase screen time — through notifications, endless scrolling, and reward systems. Consciously observing your own usage is the first step towards spending less time mindlessly on tech devices.',
    didYouKnow: 'Teenagers spend an average of more than seven hours a day on screens — not counting school hours.',
    firstAppearance: 's1e03c01',
  },
  {
    id: 'screenshot',
    title: 'Screenshot',
    teaser: 'A photo of what is currently visible on the screen.',
    body: 'A screenshot captures what is shown on the display — as an image. That sounds simple, but it has consequences: messages that delete themselves after reading or are marked as "private" can still be captured by screenshot and forwarded. Many misunderstandings and arguments arise from screenshots that are taken out of context.',
    didYouKnow: 'In some apps (like Snapchat) the other person is notified when you take a screenshot. In most they\'re not.',
    firstAppearance: 's1e03c01',
  },
  {
    id: 'selfie',
    title: 'Selfie',
    teaser: 'A photo of yourself — usually carefully selected.',
    body: 'A selfie is a photo you take of yourself — usually with your own phone with your arm outstretched or using the front camera. The difference from a normal photo: you immediately control how you look. And if necessary, you take seven more versions. A selfie rarely shows a random moment. It\'s usually selected, edited, or filtered. That means: it shows a version of someone — not necessarily the whole reality.',
    didYouKnow: 'Studies show that people take an average of 7–10 selfies before posting one. What looks "spontaneous" is often carefully selected.',
  },
  {
    id: 'sextortion',
    title: 'Sextortion',
    teaser: 'Blackmail on the internet using private images — the blame always lies with the perpetrator.',
    body: 'Sextortion is a form of blackmail on the internet. Someone first acts friendly or interested and tries to get others to send private or embarrassing images or videos. Afterwards the person threatens to publish or forward these if you don\'t do what they demand. Important: the blame always lies with the blackmailer, not with the child or young person. In this situation, tell a trusted adult immediately and don\'t respond alone.',
    didYouKnow: 'Sextortion affects girls and boys equally. Those affected should know: you\'re not alone, and there is help — for example from the police or at organisations like the Internet Watch Foundation.',
  },
  {
    id: 'spam',
    title: 'Spam',
    teaser: 'Unwanted messages that nobody ordered.',
    body: 'Spam is unwanted messages that nobody ordered but receives anyway. Like digital advertising in excess. Spam arrives as email, message, or comment — usually sent in bulk and automatically. Some spam messages are harmlessly annoying, others try to steal personal data.',
    didYouKnow: 'The name "spam" comes from a Monty Python sketch from the 1970s in which a restaurant serves everything with tinned meat (SPAM) — whatever you order.',
  },
  {
    id: 'streamen',
    title: 'Streaming',
    teaser: 'Watching something directly on the internet without downloading it.',
    body: 'Streaming means watching or listening to something directly on the internet without downloading it first. Like television, but without a remote that\'s never findable. Streaming works because data is transferred in real time — you see the first few seconds while the rest is still loading.',
    didYouKnow: 'Streaming now accounts for over 60% of all internet traffic. Netflix alone uses around 15% of global internet capacity.',
  },
  {
    id: 'teaser',
    title: 'Teaser',
    teaser: 'A brief preview designed to make you curious.',
    body: 'A teaser is a brief preview of something bigger. For example a small clip from a video, a film, or a new game, designed to make you curious. It doesn\'t show everything — just enough that you want to know how it continues.',
    didYouKnow: 'The English word "to tease" means "to provoke" or "to tempt" — a teaser tempts your curiosity without revealing the whole story.',
  },
  {
    id: 'trend',
    title: 'Trend',
    teaser: 'Something lots of people are doing right now — but usually not for long.',
    body: 'A trend is something that lots of people are doing right now. Important: trends end faster than you think. On the internet, trends appear and disappear within days or weeks. What everyone is doing today is already "cringe" tomorrow. Giving in to pressure to follow along just because everyone is doing it rarely pays off.',
    didYouKnow: 'The TikTok algorithm can spread a trend globally within 24 hours — something that used to take months.',
  },
  {
    id: 'viral',
    title: 'Viral',
    teaser: 'When something spreads extremely fast on the internet.',
    body: 'When something spreads extremely fast on the internet, it\'s called "going viral". Nothing to do with a cold. A post, video, or meme can reach millions of people within hours — because it\'s shared, commented on, and forwarded. Not everything that goes viral is true or important.',
    didYouKnow: 'The term comes from "virus" — because content spreads similarly to a virus: from person to person, ever further, ever faster.',
  },
];
