// src/story-v02/content/de/s1e03.de.ts
// Episode content – compact via storyBuilder helpers.

import type { Reaction } from '../../../common/types';
import { STORY_CHARACTERS as ch } from '../../../content/characters';
import type { StoryEpisodeV02 } from '../../types/storyTypes';
import {
  m, audio, typing, divider, bonusLink, sysMsg,
  privateChat, classChat, amyChat,
  opt, optSegs,
  S, inp, IT, MIT, AF, OR, AR, CH, C,
} from '../storyBuilder';

const R = (emoji: string, type?: string): Reaction => ({ emoji, type });

// ACHTUNG: Diese Charaktere müssen idealerweise in STORY_CHARACTERS ergänzt werden.
const noah = (ch as any).noah ?? { id: 'noah', name: 'Noah', avatar: 'noah' };
const farida = (ch as any).farida ?? { id: 'farida', name: 'Farida', avatar: 'farida' };
const amir = (ch as any).amir ?? { id: 'amir', name: 'Amir', avatar: 'amir' };
const emma = (ch as any).emma ?? { id: 'emma', name: 'Emma', avatar: 'emma' };

// ─────────────────────────────────────────────────────────────────────────────
// CHAPTER 1 — Finn on Fire
// ─────────────────────────────────────────────────────────────────────────────

const c01 = C('s1e03c01', 0, 'Amic 1', 'Finn on Fire', [

  S('s1e03c01_story_classchat_spam', [
    classChat(),
    sysMsg('🔔 23 neue Nachrichten'),
    sysMsg('🔔 41 neue Nachrichten'),
    sysMsg('🔔 67 neue Nachrichten'),
    m(ch.finn, '🔁 GIF', '19:20', { reactions: [R('😂')] }),
    m(ch.dominik, '▶️', '19:20', { reactions: [R('🔥')] }),
    m(ch.finn, '🔁 GIF', '19:20'),
    m(ch.mia, 'Boah, seid ihr den ganzen Tag online?', '19:21'),
    m(ch.dominik, 'Oh nein, Mia ist genervt 😢', '19:21', { reactions: [R('😂')] }),
    m(ch.dominik, '▶️', '19:21'),
    m(ch.elsa, '▶️', '19:22'),
    m(ch.finn, '🔁 GIF', '19:28', { reactions: [R('🔥')] }),
    m(ch.dominik, '▶️', '19:29', { reactions: [R('😂')] }),
    m(ch.markus, '🔥', '19:29'),
    m(ch.markus, 'Noch so ein Video, bro!'),
    m(ch.finn, '▶️', '19:34'),
    m(ch.mia, 'Genug gespamt!', '19:36'),
    m(ch.chioma, 'Mia hat recht. Ist doch schon spät 😴.', '19:40'),
    m(ch.tom, 'Ich komme grad aus dem Stall und sehe dies:', '19:45'),
    m(ch.tom, 'weitergeleitet: 🔔 67 neue Nachrichten', '19:46'),
    m(ch.tom, '😲 Habt ihr nichts Richtiges zu tun?', '19:46'),
    m(ch.dominik, 'Was kann denn wohl besser sein?', '19:46', { reactions: [R('👍')] }),
    m(ch.finn, 'bin gleich on', '19:52'),
    m(ch.mia, 'On? du bist doch schon den ganzen Tag online 😂', '19:52'),
    m(ch.finn, 'nicht klassenchat… zocken mit markus.', '19:53'),
    m(ch.mia, 'Aber morgen ist Schule!', '19:53'),
    m(ch.finn, 'passt schon', '19:54'),
  ], ['talk-act', 'self-regulation' as any]),

  inp('s1e03c01_input_classchat_reply', 'stories:s1e03.c01.input.classchatReply', {
    topics: ['talk-act'],
    promptSpeakerId: 'finn',
  }),

  S('s1e03c01_story_tom_mia_private_day2', [
    divider('Tag 2'),
    privateChat('Tom', 'Mia'),
    m(ch.tom, 'Hast du mal gesehen, bis wann Finn nachts online ist? 🤔', '7:20'),
    m(ch.mia, 'kp. Er war doch schon immer Gamer.', '7:21'),
    m(ch.tom, 'Aber nicht so..', '7:21'),
    m(ch.tom, 'Irgendwas ist anders.', '7:22'),
    m(ch.mia, 'Hm', '7:22'),
    m(ch.tom, 'Wann war er das letzte Mal mit uns Skaten? 🤔', '7:23'),
    m(ch.mia, 'Das ist ewig her.', '7:23'),
    m(ch.mia, 'Hab ich auch schon gedacht. Wär mal wieder schön.', '7:23'),
    m(ch.tom, '😊 Mit Finn meinst du?', '7:24'),
    m(ch.mia, 'Naja. Alle zusammen halt.', '7:24'),
    m(ch.tom, 'Aha! 😊', '7:24'),
    m(ch.mia, 'Nerv nicht.', '7:24'),
    m(ch.mia, 'Lass uns doch heute Nachmittag im Skatepark treffen.', '7:24'),
    m(ch.tom, 'Vielleicht kommt Finn ja mit. 😊', '7:25'),
    m(ch.mia, 'Wer weiß.', '7:25'),
    m(ch.tom, 'Frag ihn halt.', '7:26'),
    m(ch.tom, 'Ich bin dabei. 👍', '7:26'),
    sysMsg('Finn wurde hinzugefügt.'),
    m(ch.mia, '@Finn, du warst nicht bei Mathe.', '13:40'),
    m(ch.finn, 'ja und?'),
    m(ch.mia, 'Die Schubert macht sich schon Sorgen.'),
    m(ch.finn, 'ja und?'),
    m(ch.mia, 'hast du wieder die ganze Nacht gezockt?'),
    m(ch.finn, 'geht dich das was an?'),
    m(ch.tom, 'Jetzt chill mal.'),
    m(ch.finn, 'was wollt ihr eigentlich von mir?'),
    m(ch.mia, 'Wir wollen zum Skaten. Heute Nachmittag. Kommst du?'),
    m(ch.finn, 'kann jetzt nicht'),
    m(ch.tom, 'Warum, bro? Das wird cool. Wie früher.'),
    m(ch.finn, 'heute nicht'),
    m(ch.tom, 'Was ist eigentlich los mit dir, Mann?'),
    m(ch.finn, 'nichts ist los. ich hab bloß keinen bock auf das gelaber'),
    m(ch.finn, 'das muss ich mir schon von meiner mutter anhören'),
    m(ch.tom, 'Kommst du später nach?'),
    m(ch.finn, 'ja'),
    m(ch.tom, 'Wirklich?'),
    m(ch.finn, 'klar, versprochen.'),
    sysMsg('Finn hat den Chat verlassen.'),
    m(ch.mia, 'Was ist bloß los mit ihm? So kenn ich ihn gar nicht.'),
    m(ch.tom, 'Der hat doch einen Knall!'),
    m(ch.mia, 'War das so schlimm, was ich gesagt habe?'),
  ], ['talk-act', 'reflect-understand']),

  S('s1e03c01_story_finn_game_friend', [
    privateChat('Finn', 'Game-Freund', 'Du'),
    m(ch.finn, 'ich muss weg', '14:53'),
    m({ id: 'game-freund', name: 'Game-Freund', avatar: 'game-freund' } as any, 'Bro nicht jetzt'),
    m({ id: 'game-freund', name: 'Game-Freund', avatar: 'game-freund' } as any, 'Wir sind mitten im Battle'),
    m(ch.finn, 'ich muss los'),
    m({ id: 'game-freund', name: 'Game-Freund', avatar: 'game-freund' } as any, 'Das kannst du nicht machen. Ohne dich sind wir lost'),
    m({ id: 'game-freund', name: 'Game-Freund', avatar: 'game-freund' } as any, 'Zieh durch. Danach kannst du ja gehen'),
    m(ch.finn, 'ok. aber nur noch kurz'),
    divider('Später'),
    m(ch.finn, 'waaas? schon so spät???', '17:12'),
    m(ch.finn, 'mist. hab meine verabredung verpasst'),
    m({ id: 'game-freund', name: 'Game-Freund', avatar: 'game-freund' } as any, 'Reg dich nicht auf. Wir haben doch gewonnen 🔥'),
    m(ch.finn, 'jetzt ist eh zu spät'),
    m(ch.finn, '@{{chatName}} hab hier die karte für dich ausgefüllt: Charakterkarte Finn'),
    bonusLink('char-finn', 'Charakterkarte Finn', '/cards/char-finn', 'Karte ansehen →'),
  ], ['talk-act', 'self-regulation' as any]),

  inp('s1e03c01_input_finn_reply', 'stories:s1e03.c01.input.finnReply', {
    topics: ['talk-act'],
    promptSpeakerId: 'finn',
  }),

  S('s1e03c01_story_switch_to_amy', [
    amyChat(),
    m(ch.amy, 'Finn muss eigentlich los, bleibt dann aber trotzdem noch im Spiel.'),
    m(ch.amy, 'Was würdest du in so einem Moment machen?'),
  ], ['reflect-understand']),

  IT('s1e03c01_item_interrupt_impulse_game',
    'Finn muss eigentlich los, bleibt dann aber trotzdem noch im Spiel. Was würdest du in so einem Moment machen?',
    'self_regulation',
    'interrupt_impulse',
    [
      optSegs('a', 'Ich spiel in so einem Moment auch weiter und fahre später los. Wenn das Battle gerade läuft, kann man nicht raus. Das verstehen die Freunde schon.', 0,
        'Du bleibst im Spiel, obwohl du eigentlich schon los müsstest. So entscheidet der Moment für dich, nicht du selbst.',
        '👉 Am Ende fehlt dann die Zeit für das, was dir auch wichtig war.',
        '💡 Wenn du leicht die Zeit im Spiel vergisst, plane vorher: Nimm dir genug Zeit oder stell dir einen Wecker.',
      ),
      optSegs('b', 'Ich würde nur noch kurz spielen, aber es ist wirklich immer schwierig, dann auch rechtzeitig rauszugehen.', 1,
        '„Nur noch kurz“ ist genau der Punkt, an dem viele hängen bleiben.',
        '👉 Ohne, dass du es merkst, ist plötzlich viel mehr Zeit verstrichen als gedacht.',
        '💡 Wenn es dir schwerfällt, rechtzeitig auszumachen, plane ausreichend Zeit ein oder stell dir einen Wecker.',
      ),
      optSegs('c', 'Ich würde im Spiel gleich schreiben, dass ich pünktlich raus muss, und dann versuchen, es durchzuziehen.', 2,
        'Du sagst Bescheid und versuchst rauszugehen. Damit planst du voraus.',
        '👉 Jetzt kommt es darauf an, es auch wirklich durchzuziehen.',
        '💡 Wenn du dich entschieden hast: Mach den Schritt sofort, bevor du dich wieder reinziehen und ablenken lässt.',
      ),
      optSegs('d', 'Wenn mir die Verabredung wichtig ist, fange ich gar nicht erst ein neues Spiel an.', 3,
        'Du denkst einen Schritt voraus und vermeidest die Situation von Anfang an.',
        '👉 So bleibst du verlässlich bei deinem Plan.',
        '💡 Das ist oft leichter gesagt als getan – aber genau so behältst du die Kontrolle über deine Zeit.',
      ),
    ],
    ['reflect-understand'],
  ),

  AF('s1e03c01_amy_feedback_interrupt_impulse_game', 's1e03c01_item_interrupt_impulse_game'),
]);

// ─────────────────────────────────────────────────────────────────────────────
// CHAPTER 2 — Immer noch online
// ─────────────────────────────────────────────────────────────────────────────

const c02 = C('s1e03c02', 1, 'Amic 2', 'Immer noch online', [

  S('s1e03c02_story_classchat_evening', [
    classChat(),
    m(ch.dominik, 'Ah, sogar die Streber sind noch online.', '19:11'),
    m(ch.dominik, 'Ab 20 Uhr ist hier immer tote Hose. Stimmt´s Markus?'),
    m(ch.markus, 'Ja, stimmt. Finn ist natürlich auch dann noch da. Und wir.'),
    m(farida, 'Noch nach 20 Uhr? Das würde meine Mutter nie erlauben.'),
    m(ch.dominik, 'lol. Deine Mutter? Prinzesschen aus 1001 Nacht hört auf die Mama. Wie süß 😂', undefined, { reactions: [R('😂')] }),
    m(ch.igor, 'Dominik, lass sie einfach in Ruhe.'),
    m(ch.markus, 'Abends wird’s doch erst spannend.'),
    m(ch.tom, 'Leute. Schlafen ist auch nice.'),
    m(ch.dominik, 'Opa.', undefined, { reactions: [R('😂')] }),
    m(ch.markus, '@ Tom: Du musst wohl nach dem Sandmännchen ins Bett? 😂'),
    m(ch.dominik, '@ Tom: Darauf hast du keine Antwort mehr? 😅'),
    m(ch.mia, 'Tom ist offline.'),
    m(ch.dominik, 'Schläft der?'),
    m(ch.elsa, '😂'),
    m(ch.markus, '😴', undefined, { reactions: [R('😂')] }),
    divider('…'),
    m(ch.lisa, '@ Tom: Hast du deinen Teil für das Referat auch schon ausgearbeitet?'),
    m(ch.yasmin, 'Wenn irgend jemand, dann Tom - ist doch immer der erste.'),
    m(ch.lisa, 'Ich hab aber Tom gefragt.'),
    m(ch.yasmin, 'Ist ja gut, wollte nur helfen. Dann warte halt, bis er selbst antwortet - da kannst du warten, bis du schwarz wirst.'),
    m(ch.dominik, 'Ich sag’s euch: Tom antwortet eh nicht, wenn du ihm keine Brieftaube schickst. 😂'),
    m(ch.tom, '@ Lisa: Ja, ich habe meinen Teil fertig. Morgen in Bio können wir es besprechen.', '19:55'),
    m(ch.tom, 'Ich checke meine Nachrichten erst nach dem Abendessen. Das reicht. Wie ich sehe, habe ich nichts Wichtiges verpasst, obwohl ihr über 100 Nachrichten geschrieben habt. 🙄', '19:55', {
      replyTo: { speakerName: 'Dominik', text: 'Ich sag’s euch: Tom antwortet eh nicht, wenn du ihm keine Brieftaube schickst. 😂' },
    }),
    m(ch.finn, 'bro wie hältst du das aus? totaler stress so viele nachrichten zu verpassen 😟'),
    m(ch.tom, 'Gar nicht. Ganz einfach. Ich nehme das Handy gar nicht mit. Und Push-Nachrichten stell ich eh aus.'),
    m(ch.finn, 'ich würd durchdrehen'),
    m(ch.mia, 'Ja, ja, wir wissen, dass du immer nur online bist.'),
    m(ch.finn, 'hä?'),
    m(ch.mia, 'Du wolltest doch nachkommen zum Skaten.'),
    m(ch.finn, 'hab ich vergessen 🙄 chill mal'),
    m(ch.mia, 'Ich…'),
    m(ch.mia, 'Ich mein Wir'),
    m(ch.mia, 'Wir haben echt auf dich gewartet.'),
    m(ch.finn, 'ja sorry halt'),
    m(ch.mia, 'Warum bist du nicht gekommen?'),
    m(ch.finn, 'einfach so.'),
    m(ch.mia, 'Ach. War eh egal. War nämlich total lustig.'),
  ], ['talk-act', 'reflect-understand']),

  S('s1e03c02_story_tom_mia_worry', [
    privateChat('Tom', 'Mia'),
    m(ch.tom, 'Ob Finn Hilfe braucht?'),
    m(ch.mia, 'Finn?'),
    m(ch.mia, 'Quatsch, so ist er halt.'),
    m(ch.tom, 'Er ist immer nur online.'),
    m(ch.tom, 'Und wenn wir ihn mal sehen, ist er mies drauf.'),
    m(ch.tom, 'Das war er früher nicht.'),
    m(ch.mia, 'Stimmt wohl.'),
    m(ch.tom, 'Und total übermüdet ist er.'),
    m(ch.tom, 'Chioma meinte auch, er sieht total fertig aus.'),
    m(ch.mia, 'Aber was sollen wir schon tun?'),
    m(ch.mia, 'Er hört eh nicht auf mich.'),
    m(ch.tom, 'Das war doch sonst ganz anders. 😊'),
    m(ch.tom, 'Wenn ich da an die Klassenreise letztes Jahr denke…'),
    m(ch.mia, 'Hör auf!'),
    m(ch.mia, 'Das war gar nichts.'),
    m(ch.tom, 'Wenn du das sagst…'),
    m(ch.mia, 'Ja. Das sag ich.'),
    m(ch.tom, 'Naja… das sah aber ganz anders aus.'),
    m(ch.mia, 'Stopp jetzt.'),
    m(ch.mia, 'Und überhaupt: Das hilft uns jetzt auch nicht.'),
    m(ch.tom, 'Wenn das so weitergeht….'),
    m(ch.mia, 'Was ist dann?'),
    m(ch.tom, 'Ach, ich hab kein gutes Gefühl dabei.'),
  ], ['reflect-understand', 'talk-act']),

  S('s1e03c02_story_switch_to_amy', [
    amyChat(),
    m(ch.amy, 'Tom macht sich Sorgen um Finn. Mia denkt eher: „So ist er halt.“'),
    m(ch.amy, 'Was könnte hinter Finns Verhalten stecken?'),
  ], ['reflect-understand']),

  IT('s1e03c02_item_finn_behavior_perspective',
    'Tom macht sich Sorgen um Finn. Mia denkt eher: „So ist er halt.“ Was könnte hinter Finns Verhalten stecken?',
    'perspective',
    'perspectives_distinguish',
    [
      opt('a', 'Er hat keine Lust mehr auf seine Freunde und macht lieber sein eigenes Ding.', 0),
      opt('b', 'Er ist oft online und vergisst dabei einfach die Zeit.', 1),
      opt('c', 'Vielleicht ist er übermüdet, weil er so viel online ist.', 2),
      opt('d', 'Es kann mehrere Gründe geben. Vielleicht ist ihm alles zu viel geworden und er kommt selbst nicht mehr richtig klar.', 3),
    ],
    ['reflect-understand'],
  ),

  OR('s1e03c02_reflection_handle_finn',
    'Wie würdest du mit Finn umgehen?',
    {
      topics: ['reflect-understand', 'talk-act'],
      category: 'ACTION',
      bypassAi: true,
      fixedAmyReply: '👉 Wenn sich jemand verändert, gibt es oft verschiedene Wege zu reagieren.\n💡 Manche sprechen so etwas direkt an, andere fragen erstmal, wie es der Person geht, oder verbringen bewusst Zeit mit ihr.',
    },
  ),

  AR('s1e03c02_amy_reaction_handle_finn', 's1e03c02_reflection_handle_finn'),

  S('s1e03c02_story_mia_diary_bonus', [
    bonusLink('diary-mia-entry1', 'Tagebuch Mia – 1. Eintrag', '/diaries/diary_mia?entry=s1e03c02_0001', 'Eintrag öffnen →'),
  ]),
]);

// ─────────────────────────────────────────────────────────────────────────────
// CHAPTER 3 — Algorithmus
// ─────────────────────────────────────────────────────────────────────────────

const c03 = C('s1e03c03', 2, 'Amic 3', 'Algorithmus', [

  S('s1e03c03_story_classchat_algorithm', [
    divider('Tag 3'),
    classChat(),
    m(ch.yasmin, 'Gestern habe ich ein voll gutes Video gesehen.', '15:28'),
    m(ch.yasmin, 'Zu unserem Thema in Geschichte.'),
    m(ch.yasmin, 'Jetzt finde ich es nicht mehr.'),
    m(noah, 'Worum geht es denn?'),
    m(ch.yasmin, 'Römisches Reich. Das war voll einfach erklärt.'),
    m(noah, 'Hier, ich hab´s sofort.'),
    m(noah, 'Aber danach kommen nur noch Basketball-Videos.'),
    m(ch.yasmin, 'Ich finde nur andere Videos…'),
    m(ch.yasmin, 'und dann wieder nur Mode und Make-up.'),
    m(ch.yasmin, 'Nicht, dass ich was dagegen hätte 😉'),
    m(ch.yasmin, 'Jetzt hab ich’s. Ist nur heute viel weiter unten.'),
    m(emma, 'Yasmin Mode - Noah Basketball.'),
    m(emma, 'Ich wette, das ist kein Zufall 🕵️'),
    m(ch.mia, '@ Emma: Du immer mit deinen Verschwörungstheorien.'),
    m(emma, 'Im Ernst. Ich hab sogar den BEWEIS:'),
    m(emma, 'Gestern hab ich EIN Video über ein Mystery Game geschaut.'),
    m(emma, 'Jetzt bekomme ich nur noch sowas angezeigt. 🧩'),
    m(ch.yasmin, 'Das ist doch kein Beweis!'),
    m(ch.carlos, 'Ein Beweis ist es zwar nicht, aber Emma hat Recht.'),
    m(ch.carlos, 'Wenn du lange auf einem Video bleibst, merkt sich das System das.'),
    m(ch.carlos, 'Und nach und nach weiß es ziemlich gut, was dir gefällt.'),
    m(ch.finn, 'also weiß mein feed mehr über mich als ich 😅'),
    m(ch.lukas, 'Oder er weiß, wie er dich festhält.'),
    m(ch.finn, '🤔 könnte was dran sein'),
    m(ch.lisa, 'Das ist ja voll spooky 👻'),
    m(ch.yasmin, 'Ich versteh gar nichts mehr. Wo ist jetzt mein Video?'),
    m(ch.lukas, 'Wenn du genau eingibst, was du suchst, findest du es auch. Es ist vielleicht weiter unten… der Algorithmus entscheidet nur, was zuerst kommt.'),
    m(ch.yasmin, 'Wer ist dieser Algorithmus jetzt schon wieder?'),
    m(ch.carlos, 'Das ist kein Mensch. Das ist eine Regel der App, die entscheidet, was du zuerst siehst. Ein Algorithmus ist eine Anleitung. Die App merkt sich, was du magst, und zeigt dir mehr davon.'),
    m(ch.yasmin, 'Warum?'),
    m(ch.lukas, 'Die App will, dass du möglichst lange bleibst und viele Videos anschaust. Denn, wer sich langweilt, klickt weg.'),
    m(ch.lukas, 'Aber du sollst ja bleiben.'),
    m(ch.yasmin, 'Und warum will die App das?'),
    m(ch.lukas, 'Damit verdient die Plattform Geld.'),
    m(ch.yasmin, 'Aber der weiß doch nicht, was mich interessiert.'),
    m(ch.carlos, 'Doch. Durch das, was du suchst, anklickst und anschaust. Das wird alles gespeichert.'),
    m(ch.tom, '@Finn, du kriegst doch bestimmt nur noch Gaming Clips oder?'),
    m(ch.finn, 'ja logisch'),
    m(ch.finn, 'interessiert mich ja auch'),
    m(ch.lukas, 'Und der endlose Nachschub zieht dich immer weiter rein.'),
    m(ch.lukas, 'Du bist nie fertig.'),
    m(ch.lukas, 'Der nächste Post kommt sofort.'),
    m(ch.finn, 'hm, kommt mir bekannt vor'),
    m(ch.chioma, 'Mit Frau Schubert wollen wir auch nächste Woche über Algorithmen sprechen.'),
    m(ch.carlos, 'Die Schubert versteht vielleicht etwas von Genitiv und Goethe, aber von Algorithmen? 😂'),
    m(ch.chioma, 'Das Wort muss sie erst mal im Wörterbuch nachschlagen 😅', undefined, { reactions: [R('😂')] }),
    m(ch.carlos, 'Ein Lexikon für unsere Klassenlehrerin? 🤔 Das wäre keine schlechte Idee.'),
    m(ch.yasmin, 'Aha. Da ist es ja. Mein Video ist nur viel weiter nach unten gerutscht.'),
  ], ['info-check', 'reflect-understand', 'talk-act']),

  S('s1e03c03_story_switch_to_amy', [
    amyChat(),
    m(ch.amy, 'Jetzt hast du gesehen, wie Apps auswählen, was du zuerst siehst.'),
    m(ch.amy, 'Woran merkst du bei dir selbst, dass dich das beeinflusst?'),
    m(ch.amy, 'Du kannst mehrere Antworten auswählen.'),
  ], ['info-check', 'reflect-understand']),

  MIT('s1e03c03_item_algorithm_influence',
    'Woran merkst du bei dir selbst, dass dich das beeinflusst?',
    'judgement',
    'information_classify',
    [
      opt('a', 'Wenn ich mir ein Video anschaue, bekomme ich danach oft noch mehr von genau diesem Thema.', 1),
      opt('b', 'Manchmal finde ich das, was ich eigentlich gesucht habe, erst viel weiter unten.', 1),
      opt('c', 'Ich schaue oft länger weiter, als ich eigentlich wollte, weil es so viel gibt.', 1),
      opt('d', 'Mir werden Sachen vorgeschlagen, die ziemlich gut zu mir passen.', 1),
      opt('e', 'Ich weiß manchmal gar nicht, warum mir etwas angezeigt wird.', 1),
      opt('f', 'Das ist mir noch nicht aufgefallen.', 0),
    ],
    {
      minSelections: 1,
      maxSelections: 6,
      helperText: 'Du kannst mehrere Antwortoptionen auswählen.',
      topics: ['info-check', 'reflect-understand'],
    },
  ),

  S('s1e03c03_story_challenge_intro', [
    m(ch.amy, 'Lust auf ein kleines Duell? 💪'),
    m(ch.amy, 'Du gegen den Algorithmus:'),
    m(ch.amy, 'Er will, dass du weiterscrollst.'),
  ], ['problem-solving']),

  CH('s1e03c03_challenge_algorithm_exit',
    '👉 Schaffst du es, einmal auszusteigen?',
  ),

  inp('s1e03c03_input_after_challenge', 'stories:s1e03.c03.input.afterChallenge', {
    topics: ['talk-act'],
    promptSpeakerId: 'amy',
  }),

  S('s1e03c03_story_newspaper_bonus', [
    bonusLink('weekly-4-david-gegen-goliath', 'Schülerzeitung: Chioma: Weekly 4 - David gegen Goliath', '/newspaper/weekly-4-david-gegen-goliath', 'Artikel öffnen →'),
  ], ['info-check']),
]);

// ─────────────────────────────────────────────────────────────────────────────
// CHAPTER 4 — Schülerzeitung
// ─────────────────────────────────────────────────────────────────────────────

const c04 = C('s1e03c04', 3, 'Amic 4', 'Schülerzeitung', [

  S('s1e03c04_story_newsroom_structure', [
    divider('Tag 4'),
    privateChat('Aylin', 'Carlos', 'Jonas', 'Chioma'),
    m(ch.aylin, 'Voll witzig die Redaktionssitzung heute 🤩', '15:20', { reactions: [R('👍')] }),
    m(ch.jonas, 'Ja, könnten wir echt öfter machen.'),
    m(ch.chioma, 'War schön, aber…'),
    m(ch.aylin, 'Aber was?'),
    m(ch.chioma, 'Aber, wenn wir wirklich eine Schülerzeitung machen wollen, brauchen wir auch eine klare Struktur.'),
    m(ch.chioma, 'Davon haben wir gar nicht gesprochen.'),
    m(ch.aylin, 'Wenn ich mich richtig erinnere, bist du gerade erst neu oder?'),
    m(ch.carlos, 'Ich finde, Chioma hat Recht.'),
    m(ch.carlos, 'Ich mach eh die Technik.'),
    m(ch.carlos, 'Das ist nicht neu.'),
    m(ch.carlos, 'Und ich kann auch über Technik-Kram schreiben.'),
    m(ch.jonas, 'Ich nehm Musik.'),
    m(ch.jonas, 'Da kenn ich mich wenigstens aus.'),
    m(ch.aylin, 'Ok.'),
    m(ch.aylin, 'Ich mach ja schon das Layout.'),
    m(ch.aylin, 'Und schreib über KI und so.'),
    m(ch.aylin, 'Und du? Chioma?'),
    m(ch.chioma, 'Was haltet ihr von einem Thema der Woche? Immer ein aktuelles Thema.', undefined, { reactions: [R('👍')] }),
    m(ch.jonas, 'Ja, das ist cool.'),
    m(ch.chioma, 'Und ich kann mich um die Organisation kümmern, wenn ihr wollt.'),
    m(ch.aylin, 'Soll das etwa heißen, du willst Chef-Redakteurin sein?'),
    m(ch.chioma, 'Nein, das mein ich nicht.'),
    m(ch.aylin, 'Klingt aber danach.'),
    m(ch.carlos, '@Aylin: Willst DU lieber die Organisation übernehmen?'),
    m(ch.aylin, 'Äh - nein!'),
    m(ch.carlos, 'Na siehst du. Ich auch nicht.'),
    m(ch.carlos, 'Chioma ist doch geeignet dafür.'),
    m(ch.jonas, 'Ich find auch. Lass sie das machen.'),
    m(ch.aylin, 'Aber sie ist gerade neu.'),
    m(ch.carlos, 'Stimmen wir ab.'),
    m(ch.chioma, 'Lass doch. Ich möchte mich wirklich nicht aufdrängen.'),
    m(ch.carlos, 'Tust du nicht. Die Organisation wollte nie jemand übernehmen.'),
    m(ch.jonas, 'Stimmt. Hat Alvarez auch schon immer gesagt.'),
    m(ch.chioma, 'Dann könnte er das vielleicht klären.'),
    m(ch.carlos, 'Wir stimmen jetzt ab und gehen mit dem Ergebnis zu ihm.'),
    m(ch.jonas, 'So machen wir es.'),
    m(ch.carlos, 'Aylin?'),
    m(ch.aylin, 'In Ordnung. 🙂'),
    m(ch.carlos, 'Umfrage (Abstimmung zur Wahl des Chef-Redakteurs/ -Redakteurin: Aylin: 1 Stimme, Carlos: 0 Stimmen, Chioma: 2 Stimmen, Jonas: 0 Stimmen, 1 Enthaltung)'),
    m(ch.carlos, 'And the winner is…'),
    m(ch.jonas, 'Chioma 🎉'),
    m(ch.aylin, 'Glückwunsch.'),
    m(ch.chioma, 'Danke.'),
    m(ch.chioma, 'Also, nur, wenn’s für alle ok ist.'),
    m(ch.aylin, 'Ist ok.'),
    m(ch.chioma, 'Super. Dann spreche ich als erstes mit Herrn Alvarez.'),
    m(ch.aylin, 'Das übernehme ich 😊'),
    m(ch.carlos, 'War ja klar 😀'),
    m(ch.chioma, 'Sonst noch etwas?'),
    m(ch.carlos, 'Ja, unbedingt.'),
    m(ch.carlos, 'Wir sollten ein Schubert-Lexikon auf der Homepage der Schülerzeitung einführen.'),
    m(ch.chioma, 'Ein was? 😂'),
    m(ch.carlos, 'Ein Schubert-Lexikon für unsere Klassenlehrerin.'),
    m(ch.carlos, 'Mit allen Worten rund um Social Media und Internet, die die Schubert nicht kennt.'),
    m(ch.aylin, 'Dann brauchst du aber viel Speicherplatz 😄'),
    m(ch.chioma, 'Super Idee so ein Wörterbuch.'),
    m(ch.chioma, 'Kümmerst du dich darum?'),
    m(ch.carlos, 'Claro.'),
    m(ch.carlos, 'Ich könnte es schon online stellen.'),
    m(ch.carlos, 'Und dann nach und nach mit neuen Einträgen erweitern.'),
    m(ch.carlos, 'Was meint ihr?'),
    m(ch.aylin, 'Du meinst zum Redaktionsschluss Ende des Monats?'),
    m(ch.jonas, 'Sollen wir wirklich so lange warten?'),
    m(ch.jonas, 'Ist die Regel mit dem Redaktionsschluss einmal im Monat nicht aus dem letzen Jahrhundert, als eine Zeitung noch gedruckt wurde?'),
    m(ch.aylin, 'Also gut. Regeländerung.'),
    m(ch.aylin, 'Wenn Frau Chef-Redakteurin einverstanden ist?'),
    m(ch.chioma, 'Klar, klingt gut. Entscheiden tun wir doch immer noch gemeinsam. 😊'),
    m(ch.aylin, 'Und ich schreib einen Artikel über Algorithmen.'),
    m(ch.aylin, 'Ich glaub, das ist gestern noch nicht jedem klar geworden.'),
    m(ch.jonas, 'Cool! Und wie die Algorithmen unsere Zeit am Bildschirm beeinflussen.'),
    m(ch.aylin, 'Genau.'),
    m(ch.aylin, 'Ähm… ich hab dazu übrigens auch schon was entdeckt. 📸'),
    m(ch.chioma, 'Was denn?'),
    m(ch.aylin, 'Schaut mal.'),
    m(ch.aylin, 'Screenshot „Finn zuletzt online: 01:03“'),
    m(ch.jonas, 'Alter.'),
    m(ch.carlos, 'Echt jetzt?'),
    m(ch.aylin, 'Ich hab das gestern „zufällig” gesehen. 😏'),
    m(ch.aylin, '01:03 - Mitten in der Nacht!!'),
    m(ch.aylin, 'Wir schreiben doch gerade über Bildschirmzeit.'),
    m(ch.aylin, 'Das wäre der perfekte Aufhänger.'),
    m(ch.chioma, 'Moment. 🤔'),
    m(ch.chioma, 'Das ist privat.'),
    m(ch.aylin, 'Aber ohne Beispiele ist der Artikel doch langweilig.'),
    m(ch.jonas, 'Ganz unrecht hat sie nicht.'),
    m(ch.carlos, 'Ich weiß nicht.'),
    m(ch.carlos, 'Mit seinem Namen? Das wäre schon ziemlich hart.'),
    m(ch.aylin, 'Aber spannend! 🤩'),
    m(ch.chioma, 'Wir veröffentlichen keine Bloßstellung.'),
    m(ch.aylin, 'Noch nicht mal offiziell Chef-Redakteurin.'),
    m(ch.aylin, 'Und schon mimst du den Boss.'),
    m(ch.aylin, 'Pass bloß auf. Ich war früher hier als du.'),
    divider('Pause'),
    m(ch.jonas, 'Mal was anderes. Habt ihr Finn heute gesehen?'),
    m(ch.aylin, '😱 ja.'),
    m(ch.aylin, 'Der sah aus wie ein Zombie.'),
    m(ch.carlos, 'Kein Wunder.'),
    m(ch.carlos, 'Wenn er bis 01:03 noch online war.'),
    m(ch.jonas, 'Da wundert mich gar nichts.'),
    m(ch.aylin, 'Ich sag ja: Das gehört in den Artikel!'),
  ], ['fairness', 'talk-act', 'problem-solving']),

  S('s1e03c04_story_switch_to_amy', [
    amyChat(),
    m(ch.amy, 'Aylin will den Screenshot von Finn nutzen, damit der Artikel spannender wird.'),
    m(ch.amy, 'Chioma findet das unfair.'),
    m(ch.amy, 'Wie würdest du in so einer Situation entscheiden?'),
  ], ['fairness', 'reflect-understand']),

  IT('s1e03c04_item_screenshot_responsibility',
    'Aylin will den Screenshot von Finn nutzen, damit der Artikel spannender wird. Chioma findet das unfair. Wie würdest du in so einer Situation entscheiden?',
    'responsibility',
    'privacy_protect',
    [
      optSegs('a', 'Ich würde den Screenshot verwenden, damit der Artikel spannend wird. Das ist gut für die Schülerzeitung.', 0,
        'Der Artikel wird vielleicht spannender, aber auf Kosten von Finn.',
        '👉 Das wird für ihn unangenehm oder verletzend.',
        '💡 Um Inhalte spannend zu gestalten, dürfen sie nicht unfair sein. Kreative Inhalte kommen auch ohne Bloßstellung aus und werden dann oft sogar viel besser.',
      ),
      optSegs('b', 'Ich würde mich raushalten oder abstimmen lassen. Sollen die anderen entscheiden, ob wir den Screenshot nehmen.', 1,
        'Du hältst dich raus und überlässt die Entscheidung den anderen.',
        '👉 So bleibst du selbst raus, aber unterstützt faires Verhalten auch nicht.',
        '💡 Manchmal reicht schon eine Stimme, um etwas Unfaires zu stoppen.',
      ),
      optSegs('c', 'Ich würde den Screenshot eher nicht verwenden, aber trotzdem versuchen, das Thema spannend zu machen.', 2,
        'Du entscheidest dich gegen den Screenshot.',
        '👉 So bleibt der Artikel fair und kann trotzdem spannend sein.',
        '💡 Jetzt geht es darum, wie du das Thema interessant erklärst - ohne jemanden bloßzustellen.',
      ),
      optSegs('d', 'Ich würde klar sagen, dass wir den Screenshot nicht verwenden, und eine faire Lösung suchen.', 3,
        'Du setzt klare Grenzen und achtest darauf, dass niemand bloßgestellt wird.',
        '👉 Gleichzeitig suchst du nach einer fairen Lösung.',
        '💡 Genau so übernimmst du Verantwortung: du erkennst, was unfair ist und änderst auch etwas daran.',
      ),
    ],
    ['fairness', 'reflect-understand'],
  ),

  AF('s1e03c04_amy_feedback_screenshot_responsibility', 's1e03c04_item_screenshot_responsibility'),

  S('s1e03c04_story_chioma_jonas_private', [
    privateChat('Chioma', 'Jonas'),
    m(ch.chioma, 'Danke übrigens.', '19:58'),
    m(ch.jonas, 'Wofür?'),
    m(ch.chioma, 'Dass du vorhin im Chat mit Aylin nicht einfach geschwiegen hast.'),
    m(ch.jonas, 'Das war ja auch unfair von ihr.'),
    m(ch.chioma, 'Ich habe mich gefreut, dass du mir beigestanden hast. War wirklich süß von dir.'),
    m(ch.jonas, 'Immer gern. 😊'),
  ], ['talk-act', 'fairness']),

  S('s1e03c04_story_classchat_teaser', [
    classChat(),
    m(ch.dominik, '🤣 Das war der Börner! Selten so gelacht!', '12:21'),
    m(ch.markus, 'Was meinst du?'),
    bonusLink('tip-carlos-schubert-lexikon', 'Carlos’ Lexikon für die Schülerzeitung', '/newspaper/tip-carlos-schubert-lexikon', 'Artikel öffnen →'),
  ], ['talk-act']),
]);

// ─────────────────────────────────────────────────────────────────────────────
// CHAPTER 5 — Das Handy
// ─────────────────────────────────────────────────────────────────────────────

const c05 = C('s1e03c05', 4, 'Amic 5', 'Das Handy', [

  S('s1e03c05_story_classchat_mocking', [
    divider('Tag 5'),
    classChat(),
    m(ch.dominik, 'Alter, als die Schubert Finn das Phone abgenommen hat 🤣'),
    m(ch.markus, 'Ja, echt, das war so lustig.'),
    m(ch.elsa, 'Der hatte sich ja gar nicht mehr unter Kontrolle. 😂😂'),
    m(ch.elsa, 'Als hätte ihm jemand sein Beatmungsgerät genommen.'),
    m(ch.dominik, 'Oder Noah seinen Rollstuhl 🤣'),
    m(noah, 'Lass meinen Rollstuhl aus dem Spiel.'),
    m(ch.dominik, 'War nur Spaß.'),
    m(ch.dominik, 'Jedenfalls dachte ich, Finn fällt gleich in Ohnmacht.'),
    m(ch.elsa, 'Wie dumm, sich beim Tippen erwischen zu lassen.'),
    m(ch.mia, 'Die Schubert schnallt doch sonst nicht, wenn jemand tippt.'),
    m(ch.markus, 'Auch wahr.'),
    m(ch.dominik, 'Wo ist Finn jetzt eigentlich?'),
    m(ch.elsa, 'Ich glaub der läuft der Schubert hinterher 😂'),
    m(ch.dominik, 'Und bettelt um sein Handy 🤣'),
    m(ch.igor, 'Genug. Langsam übertreibt ihr.'),
    divider('Etwas später'),
    m(ch.dominik, '@Finn?', '12:55'),
    m(ch.dominik, 'Hat er sein Phone wieder?'),
    m(ch.markus, 'Glaub ich nicht.'),
    m(ch.mia, 'Vielleicht gar nicht so schlecht für ihn.'),
    m(ch.dominik, 'Was bist du denn für eine Freundin?'),
    m(ch.mia, 'Ich mein ja nur.'),
    m(ch.markus, 'Hab gesehen, wie er vorm Lehrerzimmer wartet 😂'),
    m(ch.elsa, 'Und Däumchen dreht 😂'),
    m(ch.dominik, 'Der würde alles tun.'),
  ], ['talk-act', 'fairness', 'reflect-understand']),

  inp('s1e03c05_input_classchat_reply', 'stories:s1e03.c05.input.classchatReply', {
    topics: ['talk-act'],
    promptSpeakerId: 'mia',
  }),

  S('s1e03c05_story_schubert_card', [
    m(ch.mia, '@{{chatName}}, du kennst die Schubert ja gar noch nicht.'),
    m(ch.mia, 'Hier ein paar Infos über sie: Charakterkarte Schubert'),
    bonusLink('char-schubert', 'Charakterkarte Schubert', '/cards/char-schubert', 'Karte ansehen →'),
  ], ['talk-act']),

  S('s1e03c05_story_switch_to_amy', [
    amyChat(),
    m(ch.amy, 'Im Chat machen sich viele über Finn lustig.'),
    m(ch.amy, 'Was könnte bei Finn wirklich los sein?'),
  ], ['reflect-understand', 'fairness']),

  IT('s1e03c05_item_finn_phone_perspective',
    'Im Chat machen sich viele über Finn lustig. Was könnte bei Finn wirklich los sein?',
    'perspective',
    'perspectives_distinguish',
    [
      optSegs('a', 'Finn übertreibt in dieser Situation. Ich würde nicht so panisch reagieren.', 0,
        'Du vergleichst Finn mit dir selbst.',
        '👉 So bleibt seine Sicht außen vor.',
        '💡 Alle reagieren unterschiedlich und oft gibt es gute Gründe dafür. Versuche auch die Gefühle anderer zu verstehen, statt über sie zu urteilen.',
      ),
      optSegs('b', 'Das Handy scheint Finn wirklich ziemlich wichtig zu sein.', 1,
        'Du erkennst, dass ihm das Handy wichtig ist.',
        '👉 Das ist ein erster Schritt, sein Problem zu verstehen.',
        '💡 Frag dich: Warum ist es Finn so wichtig? Versuche, erst zu verstehen, was bei jemand anderem los ist, statt sofort zu urteilen.',
      ),
      optSegs('c', 'Die anderen verstehen es vielleicht nicht, aber für Finn ist das Handy wohl sehr wichtig.', 2,
        'Du merkst, dass es zwei Sichtweisen gibt: Finn und die anderen.',
        '👉 Damit verstehst du, dass seine Reaktion für ihn einen Grund hat.',
        '💡 Auch wenn andere lachen: Du schaust genauer hin, was bei der betroffenen Person wirklich los ist.',
      ),
      optSegs('d', 'Mir würde es nicht so gehen, aber für Finn ist die Situation ernst. Vielleicht geht es ihm eher darum, was er verpasst.', 3,
        'Du betrachtest deine Perspektiv und denkst dich zusätzlich in Finn hinein, das ist stark.',
        '👉 Dir wird klar: Es geht nicht nur ums Handy, sondern um das, was dahintersteckt.',
        '💡 Wenn du das erkennst, kannst du bewusst entscheiden, wie du reagierst – und dich auch von unfairem Verhalten abgrenzen.',
      ),
    ],
    ['reflect-understand', 'fairness'],
  ),

  AF('s1e03c05_amy_feedback_finn_phone_perspective', 's1e03c05_item_finn_phone_perspective'),

  S('s1e03c05_story_tom_mia_private', [
    privateChat('Tom', 'Mia'),
    m(ch.tom, 'Finn dreht gerade innerlich komplett durch.', '12:57'),
    m(ch.mia, 'Nur wegen dem Handy?'),
    m(ch.tom, 'Für ihn ist das nicht nur ein Handy.'),
    m(ch.tom, 'Er hat fast geweint.'),
    m(ch.tom, 'Kein Witz.'),
    m(ch.mia, 'Ernsthaft?'),
    m(ch.tom, 'Er ist total nervös.'),
    m(ch.tom, 'Ich glaube, er hat richtig Panik.'),
    m(ch.tom, 'So, schnell das Handy weg. Unterricht geht weiter.', '12:59'),
  ], ['reflect-understand', 'talk-act']),

  S('s1e03c05_story_classchat_afternoon', [
    classChat(),
    m(ch.elsa, 'Maria aus der Achten hat gesagt, sie hat gehört, wie Finn die Schubert angefleht hat.', '15:35', { reactions: [R('🤣')] }),
    m(ch.mia, 'Ist das wahr?'),
    m(ch.elsa, 'Ja. Und dann hat er sie bestochen: „Ich mäh Ihnen auch den Rasen.” 🤣🤣'),
    m(ch.dominik, 'Boh. Ist ja der Hammer.'),
    m(ch.elsa, 'Sag ich doch.'),
    m(ch.dominik, 'Ist er ihr auch in den Arsch gekrochen?'),
    m(ch.elsa, '😂 Nicht auszuschließen.'),
    divider('Später am Nachmittag'),
    m(ch.finn, 'habs wieder', '17:14'),
    m(ch.dominik, 'Na also.'),
    m(ch.dominik, 'Drama um nichts.'),
    m(ch.elsa, 'Hast du wirklich gedacht, du stirbst ohne?'),
    m(ch.finn, 'halt die klappe'),
  ], ['talk-act', 'fairness']),
]);

// ─────────────────────────────────────────────────────────────────────────────
// CHAPTER 6 — Offline-Zeit
// ─────────────────────────────────────────────────────────────────────────────

const c06 = C('s1e03c06', 5, 'Amic 6', 'Offline-Zeit', [

  S('s1e03c06_story_chioma_tom_private', [
    divider('Tag 6'),
    privateChat('Chioma', 'Tom'),
    m(ch.chioma, 'Wie Finn reagiert hat, als Frau Schubert sein Handy eingezogen hat.', '7:13'),
    m(ch.tom, 'Das war echt erschreckend.'),
    m(ch.chioma, 'Find ich auch.'),
    m(ch.chioma, 'Und alle machen Witze darüber.'),
    m(ch.tom, 'Dominik halt.'),
    m(ch.chioma, 'Meinst du, er ist wirklich so abhängig vom Handy?'),
    m(ch.tom, 'Er scheint nicht mehr von all dem weg zu kommen.'),
    m(ch.chioma, 'Von all dem? Was meinst du?'),
    m(ch.tom, 'Aus dem Online-Ding.'),
    m(ch.tom, 'Chat, Game, Videos.'),
    m(ch.tom, 'Alles gleichzeitig.'),
    m(ch.chioma, 'Und was hilft da?'),
    m(ch.tom, 'Pausen.'),
    m(ch.chioma, 'So wie du das machst?'),
    m(ch.tom, 'Ja, genau.'),
    m(ch.tom, 'Sonst merkt man gar nicht mehr, was man eigentlich alles online macht.'),
    m(ch.chioma, 'Hm.'),
    m(ch.chioma, 'Vielleicht sollten wir das alle mal ausprobieren.'),
    m(ch.chioma, 'So eine freiwillige Offline-Zeit.'),
    m(ch.chioma, 'Ich habe davon gelesen. Ist gerade voll der Trend.'),
    m(ch.tom, 'Alle in der Klasse meinst du? 🤔'),
    m(ch.tom, 'Könnte funktionieren.'),
    m(ch.tom, 'Muss aber wirklich freiwillig sein.'),
    m(ch.chioma, 'Ich schlage es einfach mal vor. Kennen sie ja von mir als Regeltante 😂'),
  ], ['problem-solving', 'reflect-understand', 'talk-act']),

  S('s1e03c06_story_classchat_offline_time', [
    classChat(),
    m(ch.chioma, 'Kurze Idee an alle.', '14:40'),
    m(ch.chioma, 'Wie wäre es mit einer freiwilligen Offline-Zeit?'),
    m(ch.finn, 'wozu das?'),
    m(ch.mia, 'Ich lass mir nichts vorschreiben.'),
    m(ch.chioma, 'Es schreibt dir ja niemand etwas vor.'),
    m(ch.mia, 'Doch, das versuchst du doch gerade.'),
    m(ch.mia, 'Und nur weil manche in der Klasse ihr Handy nicht im Griff haben, brauch ich nicht gleich neue Regeln.'),
    m(ch.chioma, 'So meine ich es nicht.'),
    m(ch.mia, 'Genau so fühlt sich das an.'),
    m(ch.dominik, 'Offline-Zeiten? Zum Teufel'),
    m(ch.dominik, 'Regelqueen 2.0 💀'),
    m(ch.markus, 'Jetzt kommt wieder der Moralpodcast 😂'),
    m(ch.elsa, 'Wer braucht sowas?'),
    m(ch.tom, 'Hört mal. Ist doch freiwillig.'),
    m(ch.finn, 'dann ist doch alles easy.'),
    m(ch.finn, 'muss ja keiner mitmachen'),
    m(ch.finn, 'also ich brauch so was nicht'),
    m(ch.tom, 'Du warst gestern wieder nach Mitternacht noch online.'),
    m(ch.finn, 'stalkst du mich jetzt etwa?'),
    m(ch.chioma, 'Er meint’s doch nicht böse.'),
    m(ch.finn, 'du jetzt auch noch?'),
    m(ch.finn, 'ob und wann ich online bin, geht euch gar nichts an'),
    divider('Pause'),
    m(ch.chioma, 'Vielleicht ist das Problem nicht, OB wir online sind.'),
    m(ch.chioma, 'Sondern wann und warum.'),
    m(ch.tom, 'Oder ob wir noch selbst entscheiden.'),
    m(ch.dominik, 'Ihr seid echt empfindlich.'),
    m(ch.finn, 'bin dann mal weg. ich geh jetzt zocken'),
  ], ['talk-act', 'self-regulation' as any, 'reflect-understand']),

  S('s1e03c06_story_switch_to_amy', [
    amyChat(),
    m(ch.amy, 'Tom sagt: „Es geht darum, ob wir noch selbst entscheiden.“'),
    m(ch.amy, 'Woran merkst du bei dir selbst, ob du gerade wirklich selbst entscheidest oder einfach weitermachst, ohne nachzudenken?'),
  ], ['reflect-understand']),

  IT('s1e03c06_item_self_deciding',
    'Tom sagt: „Es geht darum, ob wir noch selbst entscheiden.“ Woran merkst du bei dir selbst, ob du gerade wirklich selbst entscheidest oder einfach weitermachst, ohne nachzudenken?',
    'self_regulation',
    'steer_attention',
    [
      optSegs('a', 'Ich denke darüber gar nicht nach. Ich mache einfach weiter, solange es Spaß macht.', 0,
        'Du lässt einfach laufen und denkst nicht darüber nach.',
        'So entscheidet die Situation oder das Programm für dich – nicht du selbst.',
        '💡 Wenn du kurz stoppst und dich fragst: „Ist es jetzt Zeit für etwas anderes?“, bekommst du die Kontrolle zurück.',
      ),
      optSegs('b', 'Mir fällt manchmal ein, dass ich eigentlich etwas anderes machen wollte, mache aber meistens trotzdem weiter.', 1,
        'Du merkst, dass du eigentlich etwas anderes vorhattest, bleibst aber trotzdem dran.',
        '💡 Genau dieser Moment ist wichtig. Wenn du ihn erkennst, kannst du bewusst entscheiden, ob es Zeit ist, aufzuhören.',
      ),
      optSegs('c', 'Ich merke, wenn es zu viel wird, und versuche dann aufzuhören.', 2,
        'Du merkst, wann es dir zu viel wird, und versuchst gegenzusteuern.',
        '💡 Je schneller du reagierst, desto leichter fällt es dir, wirklich aufzuhören.',
      ),
      optSegs('d', 'Ich entscheide vorher, wann ich aufhöre, und halte mich dann auch daran.', 3,
        'Du planst voraus und setzt dir klare Grenzen. So bleibst du bei deiner Entscheidung, auch wenn es gerade spannend ist.',
        '💡 Das ist echte Selbst-Kontrolle: Du entscheidest vorher – und nicht erst im Moment.',
      ),
    ],
    ['reflect-understand'],
  ),

  AF('s1e03c06_amy_feedback_self_deciding', 's1e03c06_item_self_deciding'),

  S('s1e03c06_story_tom_mia_after', [
    privateChat('Tom', 'Mia'),
    m(ch.tom, 'Warum regt dich das so auf?', '15:10'),
    m(ch.mia, 'Weil ich für mich selbst entscheiden will.'),
    m(ch.tom, 'Genau darum geht’s doch. Um bewusste Entscheidung.'),
    m(ch.mia, 'Und weil ich keinen Bock hab, dass plötzlich alle wegen Finn ihr Leben ändern sollen.'),
    m(ch.tom, 'Aber es wäre genau das, was er jetzt braucht.'),
    m(ch.mia, 'Finn kann mich mal.'),
  ], ['talk-act', 'reflect-understand']),
]);

// ─────────────────────────────────────────────────────────────────────────────
// CHAPTER 7 — Event
// ─────────────────────────────────────────────────────────────────────────────

const c07 = C('s1e03c07', 6, 'Amic 7', 'Event', [

  S('s1e03c07_story_newsroom_argument', [
    divider('weiter Tag 6'),
    privateChat('Aylin', 'Carlos', 'Jonas', 'Chioma'),
    m(ch.chioma, 'Und, wie kommt ihr voran?', '17:35'),
    m(ch.carlos, 'Hier der Link zum Lexikon. Schaut mal rein.'),
    m(ch.chioma, 'Hat Herr Alvarez drüber geschaut?'),
    m(ch.carlos, 'Klar, ist genehmigt.'),
    m(ch.aylin, 'Ich arbeite gerade an dem Artikel über Bildschirmzeit.'),
    m(ch.carlos, 'Schon fertig?'),
    m(ch.aylin, 'Wie denn?'),
    m(ch.aylin, 'Ich weiß ja immer noch nicht, ob ich den Screenshot benutzen kann?'),
    m(ch.chioma, 'Das hatten wir doch schon. Das können wir nicht bringen.'),
    m(ch.aylin, 'Aber Leser wollen das. 💪 Die ganze Schule wird sich darauf stürzen.'),
    m(ch.aylin, 'Denk nur an die Zahl der Likes! 🤩'),
    m(ch.chioma, 'Der arme Finn. 😞'),
    m(ch.aylin, 'Das hätte er sich vorher überlegen müssen.'),
    m(ch.jonas, '01:03?'),
    m(ch.jonas, 'Das ist schon heftig. 🤔'),
    m(ch.chioma, 'Es ist privat. 🤐'),
    m(ch.aylin, 'Es zeigt doch genau das Problem.'),
    m(ch.aylin, 'Auch andere sind nachts online.'),
    m(ch.chioma, 'Dann schreiben wir das allgemein.'),
    m(ch.aylin, 'Das liest doch keiner. 🥱'),
    m(ch.carlos, 'Da hat sie einen Punkt.'),
    m(ch.carlos, 'Oder du schreibst „ein Schüler aus der 7B“.'),
    m(ch.chioma, 'Und jeder weiß trotzdem, wer gemeint ist?'),
    divider('Pause.'),
    m(ch.aylin, 'Du bist echt pingelig!'),
    m(ch.chioma, 'Ich nenne das fair!'),
    m(ch.aylin, 'Ich nenne das langweilig!'),
    m(ch.carlos, 'Okay stopp!!'),
  ], ['fairness', 'talk-act']),

  S('s1e03c07_story_classchat_event', [
    divider('Tag 7'),
    classChat(),
    m(ch.finn, 'wer ist heute abend on', '13:48'),
    m(ch.markus, 'Safe'),
    m(ch.dominik, 'Klar. Du auch?'),
    m(ch.finn, 'ja, muss heute eh rein'),
    m(ch.tom, 'Wieso musst du?'),
    m(ch.finn, 'event'),
    m(ch.finn, 'es gibt einen neuen skin'),
    m(ch.finn, 'nur heute bis 23:59'),
    m(ch.markus, 'Danach kriegt man ihn nicht mehr.'),
    m(ch.dominik, 'Oder muss Geld dafür zahlen.'),
    m(ch.dominik, 'Klassiker.'),
    m(ch.tom, 'Moment mal.'),
    m(ch.tom, 'Das ist doch Absicht.'),
    m(ch.finn, 'hä?'),
    m(ch.tom, 'Damit du auf jeden Fall wieder spielst.'),
    m(ch.carlos, 'Tom hat recht.'),
    m(ch.carlos, 'Das nennt sich limitierte Events.'),
    m(ch.carlos, 'Wenn etwas nur kurz verfügbar ist, wollen es alle sofort.'),
    m(emma, 'Oh!'),
    m(emma, 'So was Ähnliches gibt´s auch bei meiner Sprach-App.'),
    m(emma, 'Wenn ich einen Tag nichts mache, ist meine Serie weg 😭'),
    m(emma, 'Ich hab schon 32 Tage Streak.'),
    m(emma, 'Gestern hab ich extra noch schnell eine Übung gemacht.'),
    m(ch.tom, 'Obwohl du keine Lust hattest?'),
    m(emma, 'Ja.'),
    m(emma, 'Sonst wäre alles weg gewesen.'),
    m(ch.carlos, 'Genau das ist der Trick.'),
    m(ch.carlos, 'Viele Apps wollen, dass du jeden Tag zurückkommst.'),
    m(ch.lukas, 'Die Idee kommt ursprünglich eher aus Fitness- oder Lern-Apps.'),
    m(ch.lukas, 'Da kann so eine Serie helfen, um den Schweinehund zu überwinden. Und so kann man mehr erreichen.'),
    m(ch.carlos, 'Genau. Um ein eigenes Ziel zu verfolgen.'),
    m(ch.carlos, 'In Spielen hilft sie aber oft eher der App als dir.'),
    m(ch.lukas, 'Die Frage ist also:'),
    m(ch.lukas, 'Hilft dir der Trick wirklich?'),
    m(ch.carlos, 'Oder hilft er nur der App, Geld zu verdienen?'),
    m(emma, 'Man kann in meiner App sogar so ein Freeze kaufen.'),
    m(emma, 'Damit die Serie nicht kaputt geht.'),
    m(ch.tom, 'Also zahlen Leute Geld…'),
    m(ch.tom, 'nur damit eine Zahl weiterläuft?'),
    m(ch.carlos, 'Sí.'),
    m(ch.tom, 'Und in Finns Spiel sind es halt Skins und Events.'),
    m(ch.carlos, 'Genau.'),
    m(ch.carlos, 'Alles psychologische Tricks.'),
    m(ch.chioma, 'Ah ich versteh: „Nur einmal kurz.“'),
    m(ch.tom, 'Und plötzlich ist Mitternacht.'),
    m(ch.finn, 'leute, ist doch nur ein spiel'),
    m(ch.tom, 'Und wann warst du zuletzt beim Skaten? 🛹', '13:57'),
    divider('Kurze Pause.'),
    m(ch.tom, 'Kommst du heute? 15:30 Uhr?', '14:00'),
    m(ch.finn, 'klar'),
    m(ch.mia, 'Sonst sag lieber gleich, dass du nicht kommst.'),
    m(ch.mia, 'Wär auch egal.'),
    m(ch.finn, 'doch doch, ich komm. 15:30 Uhr'),
    m(ch.finn, 'aber ich kann nicht so lange'),
    m(ch.markus, '@Finn: Komm rechtzeitig! Das Event wartet nicht auf uns.'),
  ], ['info-check', 'reflect-understand', 'talk-act']),

  inp('s1e03c07_input_event_reply', 'stories:s1e03.c07.input.eventReply', {
    topics: ['talk-act'],
    promptSpeakerId: 'finn',
  }),

  S('s1e03c07_story_switch_to_amy', [
    amyChat(),
    m(ch.amy, 'Ein Event ist nur heute verfügbar und viele Freunde reden darüber.'),
    m(ch.amy, 'Was würdest du machen du, wenn du merken würdest: Das gibt’s nur heute, aber du hast eigentlich etwas anderes vor?'),
  ], ['reflect-understand']),

  IT('s1e03c07_item_limited_event',
    'Ein Event ist nur heute verfügbar und viele Freunde reden darüber. Was würdest du machen du, wenn du merken würdest: Das gibt’s nur heute, aber du hast eigentlich etwas anderes vor?',
    'self_regulation',
    'steer_attention',
    [
      optSegs('a', 'Das Event ist nur heute? Dann will ich dabei sein. Das ist doch wirklich etwas Besonderes.', 0,
        'Du lässt dich von der Aktion beeinflussen.',
        'Die Werbung wirkt und du reagierst direkt darauf, ohne groß nachzudenken.',
        '💡 Frag dich: Will ich das wirklich – oder entscheidet die Werbung über mich?',
      ),
      optSegs('b', 'Ich hatte eigentlich etwas anderes vor. Aber bei dem einmaligen Event möchte ich unbedingt dabei sein. Hoffentlich gibt es keinen Stress.', 1,
        'Du merkst, dass dich das Event stark reizt. Deshalb fällt es dir schwer, die Alternativen zu betrachten und abzuwägen.',
        '💡 Dieses Gefühl ist normal. Wichtig ist: Die Werbung will genau das erreichen – dass du denkst, du könntest etwas verpassen.',
        'Du kannst trotzdem selbst entscheiden, wie du deine Zeit nutzt.',
      ),
      optSegs('c', 'Mir ist klar, dass das eine Art Werbung ist. Aber das Event ist halt wirklich spannend - eine schwierige Entscheidung.', 2,
        'Du bemerkst die Absicht, die hinter der Werbung steckt und hinterfragst sie.',
        'Damit bist du nicht mehr einfach im Sog drin.',
        '💡 Wenn du kurz nachdenkst, kannst du bewusst wählen – statt automatisch mitzugehen. Betrachte dabei nicht nur deine Lust in dem Moment, sondern auch die Folgen.',
      ),
      optSegs('d', 'Ich entscheide bewusst und unabhängig von der Aktion – auch wenn andere versuchen, mich zu beeinflussen.', 3,
        'Du triffst deine Entscheidung unabhängig vom Druck der Werbung.',
        'So bleibst du bei dem, was dir wirklich wichtig ist.',
        '💡 Genau so behältst du die Kontrolle – auch wenn es gerade verlockend ist.',
      ),
    ],
    ['reflect-understand'],
  ),

  AF('s1e03c07_amy_feedback_limited_event', 's1e03c07_item_limited_event'),

  OR('s1e03c07_reflection_urge_moment',
    'Was geht dir in so einem Moment durch den Kopf, wenn du merkst: Ich will das jetzt unbedingt machen?',
    { topics: ['reflect-understand'], category: 'FEELING' },
  ),

  AR('s1e03c07_amy_reaction_urge_moment', 's1e03c07_reflection_urge_moment'),

  S('s1e03c07_story_finn_mia_deleted', [
    privateChat('Finn', 'Mia'),
    sysMsg('Finn hat 2 verpasste Anrufe'),
    m(ch.mia, 'Finn, wann kommst du? Wir warten schon.', '15:44'),
    m(ch.mia, 'Das ist doch nicht dein Ernst?', '15:53'),
    m(ch.mia, 'Wenn du wieder nicht kommst, …', '15:59'),
    m(ch.finn, 'Sprachnachricht aufgenommen aber nicht gesendet:', '18:20'),
    m(ch.finn, 'mia, es tut mir echt so leid. bin auf dem sofa eingepennt', '18:21'),
    m(ch.finn, 'aber du glaubst mir bestimmt eh nicht', '18:21'),
    m(ch.finn, 'ich würde mir auch nicht mehr glauben. aber es stimmt', '18:22'),
    m(ch.finn, 'sorry mia', '18:22'),
    sysMsg('Nachrichten gelöscht.'),
    bonusLink('tip-carlos-game-tricks', 'Carlos: Bonusartikel „Die Tricks der Spiele – warum du immer wieder zurückkommst“', '/newspaper/tip-carlos-game-tricks', 'Artikel öffnen →'),
  ], ['talk-act', 'reflect-understand']),
]);

// ─────────────────────────────────────────────────────────────────────────────
// CHAPTER 8 — Jahrmarkt
// ─────────────────────────────────────────────────────────────────────────────

const c08 = C('s1e03c08', 7, 'Amic 8', 'Jahrmarkt', [

  S('s1e03c08_story_classchat_notifications', [
    divider('Tag 8'),
    classChat(),
    sysMsg('🔔 62 neue Nachrichten'),
    sysMsg('🔔 24 neue Nachrichten'),
    m(ch.dominik, 'Wer ist heute 19 Uhr online?', '15:28'),
    m(ch.markus, 'Bin safe.'),
    m(ch.elsa, 'Ich auch.'),
    m(ch.tom, 'Ich nicht. Bin im Stall.'),
    m(ch.mia, 'Warum 19 Uhr? Was soll da sein?'),
    m(ch.mia, 'Ich weiß noch nicht.'),
    m(ch.mia, '@Tom Dann kommst du heute gar nicht zum Skaten?'),
    m(ch.tom, 'Ich kann nicht. Aber vielleicht geht Finn?'),
    m(ch.mia, 'lol. Das glaubst du ja wohl selbst nicht.'),
    m(ch.dominik, 'Dein Göttergatte skatet nicht mehr mit dir? 😢'),
    m(ch.mia, 'Er ist nicht mein Göttergatte.'),
    m(ch.dominik, 'Ärger im Paradis?'),
    m(ch.mia, 'Gar nicht.', '15:35'),
    divider('Später.'),
    m(ch.finn, 'sorry war kurz weg', '15:47'),
    m(ch.dominik, 'Kurz? Du antwortest ja gar nicht mehr.'),
    m(ch.markus, 'Und im Game gestern warst du auch nicht. Hab ewig auf dich gewartet.'),
    m(ch.finn, 'ging halt nicht'),
    m(ch.tom, '??'),
  ], ['talk-act', 'reflect-understand']),

  S('s1e03c08_story_mia_finn_private', [
    privateChat('Mia', 'Finn'),
    m(ch.finn, 'Mia?', '16:31'),
    m(ch.mia, 'Was willst du?'),
    typing('Finn tippt.'),
    typing('Finn löscht.'),
    typing('Finn tippt.'),
    m(ch.finn, 'alles klar?'),
    m(ch.mia, 'Klar.'),
    typing('Finn tippt.'),
    typing('Finn löscht.'),
    typing('Finn tippt'),
    m(ch.finn, 'gut'),
    m(ch.mia, 'Warum schreibst du mir?'),
    typing('Finn tippt.'),
    typing('Finn löscht.'),
    m(ch.finn, 'nur so.'),
    m(ch.mia, 'Alles klar?'),
    m(ch.finn, 'klar'),
    m(ch.mia, 'Sicher?'),
    typing('Finn tippt.'),
    typing('Finn löscht.'),
    typing('Finn tippt.'),
    m(ch.finn, 'eigentlich nicht so.'),
    m(ch.mia, 'Warum nicht?'),
    m(ch.finn, 'es fühlt sich grad an, als würde alles gleichzeitig passieren'),
    m(ch.mia, 'Was meinst du?'),
    m(ch.finn, 'ich weiß selbst nicht'),
    m(ch.finn, 'es ist wie… keine ahnung'),
    m(ch.mia, 'Wie was?'),
    m(ch.finn, 'weißt du noch als wir letzten herbst auf dem jahrmarkt waren?'),
    m(ch.mia, 'Klar.'),
    m(ch.finn, 'dort war alles so bunt und spannend. so lustig, dass wir nicht aufhören konnten'),
    m(ch.mia, 'Stimmt. Wir sind immer und immer wieder in die drehenden Tassen 🥴'),
    m(ch.finn, '… bis wir uns gegenseitig angekotzt haben.'),
    m(ch.mia, 'Ich mag gar nicht daran denken.'),
    m(ch.finn, 'so ungefähr fühl ich mich'),
    m(ch.finn, 'überall lichter, tausend geräusche, alles dreht sich.'),
    m(ch.finn, 'und trotzdem zieht es mich an', '16:42'),
  ], ['reflect-understand', 'talk-act']),

  S('s1e03c08_story_switch_to_amy', [
    amyChat(),
    m(ch.amy, 'Finn merkt, dass ihn Games, Chats und das ganze Online-Ding gerade stark anziehen – obwohl ihm das alles gleichzeitig zu viel wird.'),
    m(ch.amy, 'Was ist da gerade bei ihm los?'),
  ], ['reflect-understand']),

  IT('s1e03c08_item_inner_conflict',
    'Finn merkt, dass ihn Games, Chats und das ganze Online-Ding gerade stark anziehen – obwohl ihm das alles gleichzeitig zu viel wird. Was ist da gerade bei ihm los?',
    'self_regulation',
    'steer_attention',
    [
      optSegs('a', 'Finn übertreibt einfach. So schlimm kann das doch nicht sein.', 0,
        'Du schiebst Finns Gefühl schnell weg und nimmst es nicht ernst.',
        'Dadurch übersiehst du, dass hinter seinem Verhalten ein echtes Problem stecken kann.',
        '💡 Wenn jemand überfordert wirkt, hilft es, erst nachzufragen, statt es einfach abzutun. So verstehst du besser, was wirklich los ist.',
      ),
      optSegs('b', 'Finn ist bestimmt zu lange online gewesen und deshalb genervt.', 1,
        'Du erkennst, dass die viele Online-Zeit etwas damit zu tun haben könnte.',
        'Das ist ein guter Anfang. Dass er trotzdem so viel online geht, hängt mit den Mechanismen der Spiele zusammen. Sie ziehen ihn an, während sie ihn gleichzeitig überfordern.',
        '💡 Das zu verstehen ist der erste Schritt. Um sich davon zu lösen, helfen klare Pausen, feste Grenzen und Unterstützung von anderen.',
      ),
      optSegs('c', 'Vielleicht ist es Finn mit der Zeit zu viel geworden und er merkt erst jetzt, wie sehr ihn das alles stresst.', 2,
        'Du merkst, dass Finn unter Stress steht und dass ihm alles zu viel geworden ist.',
        '💡 Wenn du Überforderung erkennst, kannst du früher gegenlenken. Oft helfen schon feste Pausen und ein ehrliches Gespräch, bevor alles kippt. Allein gegen die Mechanismen der Spiele anzukommen, ist nicht leicht.',
        '👉 erkennt Zusammenhang',
      ),
      optSegs('d', 'Die Online-Welt zieht Finn gerade stark an und gleichzeitig wird ihm das alles zu viel. Genau das macht es so schwer, aufzuhören.', 3,
        'Du erkennst den inneren Konflikt: Die Online-Welt zieht Finn gerade stark an – und gleichzeitig überfordert sie ihn.',
        'Genau das macht es so schwer, einfach aufzuhören.',
        '💡 Wenn du merkst, dass dich etwas gleichzeitig reizt und stresst, ist das oft ein Zeichen: Zeit für Abstand. Wer das früh erkennt, behält leichter die Kontrolle.',
      ),
    ],
    ['reflect-understand'],
  ),

  AF('s1e03c08_amy_feedback_inner_conflict', 's1e03c08_item_inner_conflict'),

  OR('s1e03c08_reflection_own_experience',
    'Hast du das selbst schon erlebt?',
    {
      topics: ['reflect-understand'],
      category: 'FEELING',
      bypassAi: true,
      fixedAmyReply: '',
    },
  ),

  S('s1e03c08_story_mia_finn_after_reflection', [
    privateChat('Mia', 'Finn'),
    m(ch.finn, 'bist du noch da?', '16:45'),
    m(ch.mia, 'Ja.'),
    m(ch.finn, 'sorry klingt dumm'),
    m(ch.mia, 'Gar nicht.'),
    m(ch.finn, 'bist du sauer auf mich?'),
    m(ch.mia, 'Warum sollte ich?'),
    m(ch.finn, 'ich war nicht grad freundlich in letzter zeit'),
    m(ch.finn, 'ich versteh selbst nicht wieso'),
    m(ch.mia, 'Hm.'),
    m(ch.finn, 'sorry echt'),
    bonusLink('diary-mia-entry2', 'Tagebuch Mia – 2. Eintrag', '/diaries/diary_mia?entry=s1e03c08_0002', 'Eintrag öffnen →'),
  ], ['talk-act', 'reflect-understand']),
]);

// ─────────────────────────────────────────────────────────────────────────────
// CHAPTER 9 — Hilfe
// ─────────────────────────────────────────────────────────────────────────────

const c09 = C('s1e03c09', 8, 'Amic 9', 'Hilfe', [

  S('s1e03c09_story_classchat_missing_finn', [
    divider('Tag 9'),
    classChat(),
    m(ch.chioma, 'Erster Tag der Offline-Challenge 😊 Ich meld mich dann jetzt ab aus dem Chat.', '7:12'),
    m(ch.tom, 'Bei mir bleibt das Handy heute dann auch den ganzen Tag aus.'),
    m(ch.markus, '😂 viel Spaß damit'),
    m(ch.dominik, 'Ich bin raus.'),
    m(ch.elsa, 'Ich auch.'),
    divider('Später'),
    m(ch.mia, 'Hat jemand von Finn gehört?', '12:25'),
    m(ch.elsa, 'Nein.'),
    m(ch.igor, 'Macht er vielleicht auch mit bei der Challenge?'),
    m(ch.elsa, 'Das glaubst du doch selbst nicht.'),
    m(ch.mia, 'Das erklärt doch nicht, warum er in der Schule fehlt.', undefined, {
      replyTo: { speakerName: 'Igor', text: 'Macht er vielleicht auch mit bei der Challenge?' },
    }),
    m(ch.markus, 'Er war gestern auch nicht im Game.'),
    m(ch.dominik, 'Vielleicht mäht er den Rasen der Schubert 😂'),
    m(ch.mia, 'Sehr witzig.'),
  ], ['talk-act', 'reflect-understand']),

  S('s1e03c09_story_switch_to_amy', [
    amyChat(),
    m(ch.amy, 'Mia merkt, dass es Finn nicht gut geht.'),
    m(ch.amy, 'Wie würdest du jetzt reagieren?'),
  ], ['reflect-understand', 'fairness']),

  IT('s1e03c09_item_support_finn',
    'Mia merkt, dass es Finn nicht gut geht. Wie würdest du jetzt reagieren?',
    'responsibility',
    'intervene',
    [
      optSegs('a', 'Ich wäre immer noch sauer. Finn hat mich oft hängen lassen. Damit muss er jetzt selbst klarkommen.', 0,
        'Du konzentrierst dich auf deinen Ärger und lässt Finn mit dem Problem allein.',
        'Das ist verständlich. Aber manchmal sieht man vor lauter Wut nicht, dass jemand gerade wirklich Hilfe braucht.',
        '💡 Jemandem zu helfen, dem es schlecht geht, fühlt sich richtig gut an.',
      ),
      optSegs('b', 'Ich würde ihm sagen, dass mir das leid tut, aber mich sonst raushalten.', 1,
        'Du siehst, dass es Finn schlecht geht.',
        'Das ist wichtig. Aber Mitgefühl allein verändert noch nichts.',
        '💡 Manchmal hilft schon ein kleiner Schritt: zuhören, nachfragen oder Hilfe anbieten.',
      ),
      optSegs('c', 'Ich würde ihm zuhören und raten, dass er zum Arzt gehen sollte.', 2,
        'Du nimmst Finn ernst und sagst ihm ehrlich, dass er Hilfe braucht.',
        'Damit machst du schon etwas Wichtiges.',
        '💡 Unterstützung muss nicht groß sein. Oft reicht es, jemandem zu zeigen: Du bist nicht allein. Das stärkt auch die Freundschaft.',
      ),
      optSegs('d', 'Ich würde ihm zeigen, dass ich für ihn da bin. Und mit ihm überlegen, wie ich ihm konkret helfen kann.', 3,
        'Du erkennst das Problem und wirst aktiv.',
        'So hilfst du Finn nicht nur im Moment, sondern auch beim nächsten Schritt.',
        '💡 Es ist stark, jemandem zu zeigen: Ich bin da. Genau das gibt Halt und stärkt eure Freundschaft.',
      ),
    ],
    ['reflect-understand', 'fairness'],
  ),

  AF('s1e03c09_amy_feedback_support_finn', 's1e03c09_item_support_finn'),

  S('s1e03c09_story_mia_finn_support', [
    privateChat('Mia', 'Finn'),
    m(ch.mia, 'Wo bist du?', '12:35'),
    m(ch.finn, 'bin zuhause'),
    m(ch.mia, 'Warum bist du nicht in der Schule?'),
    m(ch.mia, 'Wieder die ganze Nacht gezockt und jetzt zu müde oder was?'),
    m(ch.mia, 'So geht das nicht!', '12:36'),
    divider('Pause.'),
    m(ch.finn, 'nee', '12:38'),
    m(ch.finn, 'das ist es nicht'),
    m(ch.finn, 'mir gehts einfach nicht gut'),
    m(ch.mia, 'Oh.'),
    m(ch.mia, 'Sorry.'),
    m(ch.mia, 'Bist du krank?'),
    m(ch.finn, 'einfach alles zu viel'),
    m(ch.mia, 'Doch zu lange wach gewesen?'),
    m(ch.finn, 'das auch. aber nicht, was du jetzt denkst'),
    m(ch.finn, 'mein kopf hört einfach nicht auf zu brummen'),
    m(ch.finn, 'chat'),
    m(ch.finn, 'games'),
    m(ch.finn, 'schule'),
    m(ch.finn, 'alles gleichzeitig'),
    divider('Pause'),
    m(ch.mia, 'Und was machst du jetzt?'),
    m(ch.finn, 'muss gleich los'),
    m(ch.mia, 'Wohin?'),
    m(ch.finn, 'mama will dass ich zum arzt geh'),
    m(ch.mia, 'Zum Arzt?'),
    m(ch.mia, 'Warum?'),
    m(ch.finn, 'sie meint ich seh aus wie ein zombie'),
    m(ch.mia, 'Naja, stimmt ja auch irgendwie.'),
    m(ch.finn, 'und ich soll mal mit jemandem reden'),
    m(ch.finn, 'wegen screen-time und balance meint sie'),
    divider('Pause.'),
    m(ch.mia, 'Das ist vielleicht gar keine schlechte Idee.'),
    m(ch.finn, 'meinst du auch?'),
    m(ch.mia, 'Ja.'),
    m(ch.mia, 'Und…'),
    m(ch.finn, 'was?'),
    m(ch.mia, 'Und… du musst da auch nicht allein durch.'),
    m(ch.finn, '?'),
    m(ch.mia, 'Wenn du willst, probieren wir das gemeinsam.'),
    m(ch.finn, 'was? zum arzt gehen?'),
    m(ch.mia, 'Nein. Ich meine…'),
    m(ch.mia, 'das mit den Offline-Zeiten.'),
    m(ch.mia, 'Ich hab da wohl ein bisschen überreagiert, als Chioma das vorgeschlagen hat.'),
    m(ch.mia, 'Ich war einfach sauer auf dich.'),
    m(ch.finn, 'verstehe'),
    m(ch.mia, 'Und vielleicht hab ich deshalb gar nicht kapiert, was bei dir grad los ist.'),
    m(ch.finn, 'ich kapier´s ja selbst nicht.'),
    m(ch.mia, 'Vielleicht sind Offline-Zeiten gar kein Kontrollverlust.'),
    m(ch.mia, 'Sondern Kontrollgewinn - über eigene Entscheidungen.'),
    m(ch.finn, 'hm. vielleicht.'),
    m(ch.mia, 'Wir müssen es ja nicht perfekt einhalten. Nur ein bisschen.'),
    divider('Pause.'),
    m(ch.finn, 'ok'),
    divider('Pause.'),
    m(ch.finn, 'aber nicht schon heute oder?'),
  ], ['talk-act', 'reflect-understand', 'problem-solving']),
]);

// ─────────────────────────────────────────────────────────────────────────────
// CHAPTER 10 — Entscheiden kannst du selbst
// ─────────────────────────────────────────────────────────────────────────────

const c10 = C('s1e03c10', 9, 'Amic 10', 'Entscheiden kannst du selbst', [

  S('s1e03c10_story_classchat_offline_effect', [
    divider('Tag 10'),
    classChat(),
    m(ch.igor, '@Chioma: Das Handy beim Essen auszuschalten war gestern echt angenehm.', '15:15'),
    m(ch.markus, 'Oha. Jetzt wird’s spirituell 😂'),
    m(ch.igor, 'Echt jetzt. Hätt ich nicht gedacht.'),
    m(ch.yasmin, 'Du hast bei der Offline-Challenge auch mitgemacht?'),
    m(ch.igor, 'Klar, warum nicht?'),
    m(ch.igor, 'Das Essen war irgendwie…'),
    m(ch.chioma, 'Aromatischer oder?'),
    m(ch.igor, 'Ja, genau. Irgendwie special.'),
    m(ch.elsa, 'Klingt ja unfassbar spannend 🙄'),
    m(ch.mia, 'Ich hab’s gestern auch Nachmittag dann auch noch probiert.'),
    m(ch.tom, 'Und?'),
    m(ch.mia, 'War erst komisch. Wenn ich irgendwo warte, gucke ich sonst immer ins Handy.'),
    m(ch.mia, 'Aber war gut. Hab stattdessen dem Regen zugeguckt.'),
    m(ch.dominik, '😂😂😂'),
    m(ch.finn, 'heute skatepark?'),
    m(ch.mia, 'Und das kommt von dir? 😊'),
    m(ch.finn, 'klar'),
    m(ch.mia, 'Aber nicht, dass du uns wieder sitzen lässt. 😡'),
    m(ch.finn, '😊 bin schon da'),
    m(ch.mia, 'Was, echt?'),
    m(ch.tom, 'Warte auf uns.'),
    m(ch.markus, 'Hey. Und das Event?'),
    m(ch.finn, 'heute nicht. vielleicht morgen.'),
  ], ['talk-act', 'reflect-understand']),

  S('s1e03c10_story_private_mia_tom_finn', [
    divider('Später'),
    privateChat('Mia', 'Tom', 'Finn'),
    m(ch.mia, 'Ich dachte bei der Offline-Sache erst, jemand will mir was verbieten.', '18:53'),
    m(ch.tom, 'Und jetzt?'),
    m(ch.mia, 'Jetzt glaub ich, Chioma wollte uns einfach helfen.'),
    m(ch.finn, 'kann schon sein'),
    m(ch.finn, 'hab gestern abend handy und computer komplett ausgemacht'),
    m(ch.mia, 'Und?'),
    m(ch.finn, 'erst weird'),
    m(ch.finn, 'aber nicht schlecht.'),
    m(ch.mia, 'Sag ich doch.'),
    m(ch.finn, 'du sagst ziemlich oft kluge sachen in letzter zeit'),
    m(ch.mia, 'Gewöhn dich nicht dran 😌'),
    m(ch.tom, 'Mein Cousin hat jetzt sogar so ein Dumbphone'),
    m(ch.mia, 'Ein Dumbphone?'),
    m(ch.finn, 'so ein altes handy, mit dem man quasi nur telefonieren kann?'),
    m(ch.tom, 'Er sagt, er hatte kein Bock mehr auf den Stress.'),
    m(ch.finn, 'smart. aber so weit bin ich noch nicht 😅'),
    m(ch.finn, 'so, schluss mit chatten. Wir sehen uns morgen in der schule'),
    m(ch.mia, '😊'),
  ], ['talk-act', 'reflect-understand']),

  S('s1e03c10_story_newsroom_article', [
    divider('Tag 11'),
    privateChat('Aylin', 'Carlos', 'Jonas', 'Chioma'),
    m(ch.carlos, 'Kurzes Update.', '12:29'),
    m(ch.carlos, 'Herr Alvarez hat den Artikel gesehen.'),
    m(ch.aylin, 'Und?'),
    m(ch.carlos, 'Der Screenshot kommt nicht rein.'),
    m(ch.jonas, 'Oh.'),
    m(ch.aylin, 'Natürlich nicht. 😤'),
    m(ch.aylin, 'Sobald irgendwas spannend wird, kriegen alle Angst.'),
    m(ch.carlos, 'Alvarez meinte:'),
    m(ch.carlos, '„Journalismus heißt nicht, jemanden vorzuführen.“'),
    divider('Pause.'),
    m(ch.aylin, '😕'),
    m(ch.jonas, 'Aber der Rest vom Artikel ist echt gut.'),
    m(ch.aylin, 'Ob ihn so überhaupt jemand liest?'),
    m(ch.carlos, 'Oh. Hier ist schon ein Kommentar.'),
    m(ch.aylin, 'Was steht da?'),
    m(ch.carlos, 'Er ist von Finn.'),
    m(ch.carlos, 'Er schreibt:'),
    m(ch.carlos, '„auf euch ist echt verlass.“'),
    divider('Pause.'),
    m(ch.aylin, '🫠'),
  ], ['fairness', 'talk-act']),

  S('s1e03c10_story_lisa_yasmin_private', [
    privateChat('Lisa', 'Yasmin'),
    m(ch.lisa, 'Carlos und Chioma hängen jetzt dauernd zusammen ab.'),
    m(ch.yasmin, 'Na und?'),
    m(ch.lisa, 'Nichts weiter. Ist mir nur aufgefallen.'),
  ], ['talk-act']),

  S('s1e03c10_story_classchat_article', [
    classChat(),
    m(ch.dominik, 'Was glotzt ihr alle so auf eure Handys?'),
    m(ch.dominik, 'Ich denk, ihr seid abstinent?'),
    m(ch.igor, 'Neue Artikel in der Schülerzeitung.'),
    m(ch.finn, 'aylins artikel ist echt gut'),
    m(ch.mia, '😊'),
    m(ch.dominik, 'Wow. Finn liest jetzt Zeitung.'),
    m(ch.markus, 'Was steht drin?'),
    m(ch.finn, '„Apps und Spiele kämpfen um deine Zeit – aber entscheiden kannst du selbst”'),
    m(ch.chioma, 'Toller Schlusssatz, Aylin.'),
    m(ch.finn, 'manchmal vergisst man das halt'),
    m(ch.finn, 'dann braucht man gute freunde, die einen daran erinnern 😊'),
  ], ['info-check', 'reflect-understand', 'talk-act']),

  S('s1e03c10_story_switch_to_amy', [
    amyChat(),
    m(ch.amy, 'Finn merkt: Manchmal verliert man sich online schneller, als man denkt.'),
    m(ch.amy, 'Und manchmal helfen Freunde dabei, das zu merken.'),
    m(ch.amy, 'Was hilft dir im Alltag, wenn du merkst: Ich verliere mich in Handy-Spielen, Chats oder Videos?'),
  ], ['reflect-understand', 'problem-solving']),

  MIT('s1e03c10_item_everyday_help',
    'Was hilft dir im Alltag, wenn du merkst: Ich verliere mich in Handy-Spielen, Chats oder Videos?',
    'self_regulation',
    'keep_limits',
    [
      opt('a', 'Feste Zeiten, wann ich online bin und wann ich ausmache', 1),
      opt('b', 'Handy bewusst weglegen', 1),
      opt('c', 'Push-Nachrichten ausschalten', 1),
      opt('d', 'Freunde oder Familie erinnern mich', 1),
      opt('e', 'Erst meine Aufgaben, dann Bildschirm', 1),
      opt('f', 'Etwas ganz anderes machen (rausgehen, Sport, Musik etc.)', 1),
      opt('g', 'Etwas anderes: _________________', 1),
    ],
    {
      minSelections: 1,
      maxSelections: 7,
      helperText: 'Du kannst mehrere Antwortoptionen auswählen.',
      topics: ['reflect-understand', 'problem-solving'],
    },
  ),

  OR('s1e03c10_reflection_try_out',
    'Was möchtest du davon mal ausprobieren?',
    {
      topics: ['reflect-understand', 'problem-solving'],
      category: 'ACTION',
      bypassAi: true,
      fixedAmyReply: '',
    },
  ),

  S('s1e03c10_story_newspaper_bonus', [
    bonusLink('article-jonas-tom-offline-inseln', 'Schülerzeitung: Jonas interviewt Tom: Toms Offline-Inseln', '/newspaper/article-jonas-tom-offline-inseln', 'Artikel öffnen →'),
  ], ['info-check', 'problem-solving']),

  S('s1e03c10_story_cliffhanger', [
    divider('Cliffhanger'),
    divider('Später'),
    privateChat('Finn', 'Mia', 'Farida', 'Amir', 'Dominik', 'Igor', 'Markus'),
    m(ch.finn, 'heute war skaten echt ziemlich cool'),
    m(ch.mia, 'Wundert dich das etwa? 😉'),
    m(ch.mia, 'Bei dem tollen Wetter trifft man richtig viele aus der Schule im Skatepark.'),
    m(ch.farida, 'Wie schön. Kann man da auch einfach mal zugucken?'),
    m(ch.mia, 'Klar. Komm doch nächstes mal mit uns.'),
    m(amir, 'Das klingt gut. Mich würde das auch interessieren.'),
    m(ch.dominik, 'Und was habt ihr da verloren?'),
    m(ch.dominik, 'Was wollt ihr überhaupt hier bei uns??'),
    m(ch.igor, '@Dominik: Was willst du damit sagen?'),
    m(ch.markus, 'Leute, das kann spannend werden 😏'),
  ], ['talk-act', 'fairness']),
]);

// ─────────────────────────────────────────────────────────────────────────────
// EPISODE
// ─────────────────────────────────────────────────────────────────────────────

const s1e03De: StoryEpisodeV02 = {
  id: 's1e03',
  seasonId: 's1',
  episodeId: 's1e03',
  courseId: 's1e03',
  chapters: [c01, c02, c03, c04, c05, c06, c07, c08, c09, c10],
};

export default s1e03De;
